### ISSUE TITLE
Consider adding the information in the "Composing in the Caddyfile" article to the official documentation

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/website#105]
The information in this article is really useful for users of Caddy to figure out how `route` and `handle` work: https://caddy.community/t/composing-in-the-caddyfile/8291. Consider incorporating the information in it into the official documentation.

**Comment by mholt** [comment]
I've considered this. I think wiki articles -- if they are written well enough, generally useful, and applicable to the core experience of using Caddy, can graduate to documentation. (And I suppose some things can go the other way, from docs to wiki, if needed.) Usually, though, the wiki is the right place for _expounding_ on the core material of the docs. Go to the docs to learn how to use the software, go the wiki to learn how to master it.

However, I don't want to move so many things that the wiki becomes useless either. We don't get quite enough contributions to the wiki yet -- even examples, which so many people ask for -- so I want to promote the wiki even more.
