### ISSUE TITLE
Download Caddy docs do not describe how .deb install is configured

### ISSUE THREAD

**Issue by infogulch** [caddyserver/website#115]
At [`/docs/markdown/download.md`](https://github.com/caddyserver/website/blob/master/src/docs/markdown/download.md) the section for [Debian, Ubuntu, Raspbian](https://caddyserver.com/docs/download#debian-ubuntu-raspbian) only says:

> Installing this package automatically starts and runs Caddy for you.

But it does not describe which unit file is used ([there are two...](https://gemfury.com/caddy/deb:caddy/-/content/lib/systemd/system)) or how to query its systemd status.

I wish it would say something like (hypothetically):

> Installing this package automatically starts and runs Caddy for you.
> 
> It runs as the `caddy-api` user systemd unit, and you can check its status with `systemctl status caddy-api`

(This kind of wording wouldn't be terrible to document for the other options too.)

I ended up killing the caddy process with sudo and redefining the systemd unit file myself because I couldn't figure out how to query its status from the OS.  (Yep it's a mess... I'll clean it tomorrow.)

**Comment by mholt** [comment]
Thanks, good idea. Reworded to

> Installing this package automatically starts and runs Caddy for you as a systemd service named `caddy` using the [caddy.service](https://github.com/caddyserver/dist/blob/master/init/caddy.service) unit file.

However I don't think it's our proper place to document more than that, as that's just a matter of how to use your computer.

**Comment by infogulch** [comment]
I agree, the new wording is great: Just enough detail to describe what it does, but no more than necessary.  I like the link directly to the relevant unit file. Thank you!
