### ISSUE TITLE
http json config docs seem to be missing 

### ISSUE THREAD

**Issue by jjiang-stripe** [caddyserver/website#122]
hi! I noticed that https://caddyserver.com/docs/json/apps/http/ is now empty (and I think I remember it used to not be empty)

**Comment by mholt** [comment]
Thanks, docs server has an annoying bug I need to fix.

Anyway, should be worked around for now!

**Comment by jjiang-stripe** [comment]
oof @mholt I think there are still some pages further down the tree that are still broken (e.g. https://caddyserver.com/docs/json/apps/http/routes/ not sure if there's more) :( 
I'm personally trying to get down to the `reverse_proxy` handler page which I think is all the way down at https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy

**Comment by jjiang-stripe** [comment]
oh weirdly I think https://caddyserver.com/docs/json/apps/http/routes/ is actually supposed to point at https://caddyserver.com/docs/json/apps/http/servers/routes (the link at https://caddyserver.com/docs/json/apps/http/servers#routes is pointing at the wrong thing I guess?)

**Comment by mholt** [comment]
Hmm, try now...

I hacked this thing together about a year ago and haven't touched it since. It could use some TLC.

> oh weirdly I think https://caddyserver.com/docs/json/apps/http/routes/ is actually supposed to point at https://caddyserver.com/docs/json/apps/http/servers/routes (the link at https://caddyserver.com/docs/json/apps/http/servers#routes is pointing at the wrong thing I guess?)

Make sure to append a forward slash, or relative URLs won't work:

`https://caddyserver.com/docs/json/apps/http/servers/` <-- all the links on our docs site should always include the trailing slash; let me know if that's not the case. Thanks!

**Comment by jjiang-stripe** [comment]
looks like it's working now! thanks for the speedy fix 😁

**Comment by king5300** [comment]
[]()
