### ISSUE TITLE
Please provide `github.com/caddy-dns/hetzner` module from your download section

### ISSUE THREAD

**Issue by denisbrodbeck** [caddyserver/website#128]
Hi @mholt,

thanks for caddy — it's a terrific project and I use it a lot.

I noticed that I cannot select **Hetzner** as a *DNS provider* from the caddy download page. The implementation under `github.com/caddy-dns/hetzner` seems complete and on par with e.g. `github.com/caddy-dns/gandi` (which in turn is available from the download section).

I see that your download page calls `https://caddyserver.com/api/packages`, but that *api* does not include the *hetzner* module.

Is this, where the website's **Account** feature comes in? Do I have to create an account and add the hetzner dns module, so it gets displayed via the `https://caddyserver.com/api/packages` *api*?

Thanks in advance
Denis Brodbeck

**Comment by francislavoie** [comment]
That's right, the maintainer of the hetzner plugin should make an account on the caddyserver site to claim the package as theirs and register it as a known plugin.

**Comment by mholt** [comment]
Going to close this, since the plugin maintainer will need to take action here. Thanks!
