### ISSUE TITLE
Introduction - Info omitted (JSON)

### ISSUE THREAD

**Issue by ShalokShalom** [caddyserver/website#137]
![Screenshot_20210214_031831](https://user-images.githubusercontent.com/6344099/107866658-73eae380-6e73-11eb-9b71-e2fa362ce19a.png)

Where to place the @caddy.json? In the same folder, in which I run the command?
And why @?

https://caddyserver.com/docs/getting-started

**Comment by francislavoie** [comment]
`@` is a special argument for `curl` that tells it to read the input from a file. See https://curl.se/docs/manpage.html#-d

This assumes the file is in the same location that you run the command.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by ShalokShalom** [comment]
Well, it is meant as a bug report about the homepage. It is unclear to me, undocumented and I suggest to change this.

**Comment by francislavoie** [comment]
The guide assumes you understand how to use your computer and that you know how `curl` works. It can't teach you everything. We have to draw a line somewhere, and that line is drawn at showing you how _Caddy_ works.

**Comment by mholt** [comment]
Hmm. Yeah, the tutorial does say:

> Save this to a JSON file

So, it should be pretty clear that the .json file in the command is the one you saved. I agree with Francis that this is out of the scope of the tutorial, where one of the prerequisites is:

> Basic terminal / command line skills
