### ISSUE TITLE
Default address to admin API reports 404

### ISSUE THREAD

**Issue by ShalokShalom** [caddyserver/website#138]
![Screenshot_20210214_032258](https://user-images.githubusercontent.com/6344099/107866751-3175d680-6e74-11eb-908b-a47dfdbe4402.png)

Might be, that I make a lot of mistakes here, but this seems like your documentation is outdated?

**Comment by ShalokShalom** [comment]
https://caddyserver.com/docs/api

**Comment by francislavoie** [comment]
`http://localhost:2019` is not a valid API endpoint. Try `http://localhost:2019/config/`. See https://caddyserver.com/docs/api.

**Comment by ShalokShalom** [comment]
Well, putting it front and center kinda suggests it is. Thanks

**Comment by francislavoie** [comment]
That's the listen address, not the actual URL you should use to connect to it. Different things.

**Comment by mholt** [comment]
There are (potentially) many paths you can request at the socket. The config paths are just one of them. It's like a website, not everything is on the homepage (/).

**Comment by ShalokShalom** [comment]
I think that could be explained, rather than assumed to be known and understand.

**Comment by francislavoie** [comment]
We disagree. This is a getting started guide. Its job is to teach you how to get started _with Caddy_. Its job is _not_ to teach you everything else surrounding that. It would be a waste of time for people who already do know how the rest works. That information already exists elsewhere, and it's not our job to duplicate that information.

See this, as an explanation of how-to guides work: https://documentation.divio.com/how-to-guides/#how-to-write-good-how-to-guides

**Comment by ShalokShalom** [comment]
Its just misleading and you are rude.
