### ISSUE TITLE
How can I submit a PR against docs for a plugin

### ISSUE THREAD

**Issue by tobya** [caddyserver/website#14]
I would like to submit PR for 

https://caddyserver.com/docs/hook.service

Where do I submit a PR?  There isnt anywhere obvious at 

https://github.com/bruhs/caddy-service

**Comment by mholt** [comment]
We don't host the plugin docs; they're at the plugin websites/repositories. The only thing we have on our site is a description and maybe some examples. You'll have to ask the authors in an issue or something to update them.

Good question!
