### ISSUE TITLE
can I specify h2 protocol only while tls handshake

### ISSUE THREAD

**Issue by DdVwl6Fj3a** [caddyserver/website#146]

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for discussing documentation changes. Don't forget to fill out the thread template so we can help you!

**Comment by DdVwl6Fj3a** [comment]
> Hi! Thanks for trying Caddy!
> 
> Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

tks
