### ISSUE TITLE
Missing default value for fail_duration with passive health checks  

### ISSUE THREAD

**Issue by laurentpellegrino** [caddyserver/website#153]
I am investigating an issue with an architecture that involves the Caddy server. While investigating, I noticed that what I experience could be explained by the default value set for _fail_duration_ with passive health checks configuration:

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#passive-health-checks

What is the default value for this option? where are default values defined?

It would be helpful to add it to the docs (similarly to _max_fails_) or to mention somewhere where to find default values. 

PS: the option _max_fails_ mentions _fail_timeout_ but I guess this is _fail_duration_.

**Comment by francislavoie** [comment]
The default is zero; it's off by default. The wording already implies this IMO.

This sounds like a bit of an XY problem. What behaviour are you actually experiencing? Please ask on the [Caddy community forums](https://caddy.community). Don't forget to fill out the thread template so we can help you!
