### ISSUE TITLE
How to update the modules list on the website

### ISSUE THREAD

**Issue by ggicci** [caddyserver/website#180]
I recently implemented a [Caddy module](https://github.com/ggicci/caddy-jwt) extending the ability of Caddy's standard [authentication handler](https://caddyserver.com/docs/modules/http.handlers.authentication) with JWT authentication.

But how can I also contribute to the listing of [All Modules](https://caddyserver.com/docs/modules) on the website?

**Comment by francislavoie** [comment]
Make an account here https://caddyserver.com/account then claim your module on your account.
