### ISSUE TITLE
caddyserver.com/download broken when user agent not recognised

### ISSUE THREAD

**Issue by 0x1a8510f2** [caddyserver/website#186]
Perhaps I'm missing something, because this feels like an issue which would have been caught/reported instantly, but the page at https://caddyserver.com/download appears to have no functionality at all other than downloading a single linux/amd64 binary despite many more options being seemingly available. I've found the following issues:

- Platform selection box does nothing. The button always downloads `caddy_linux_amd64`.
- Modules/plugins cannot be selected at all.
- The search box does nothing.

These make the entire page effectively a download button, because all other functionality is unavailable.

I'm on `openSUSE Tumbleweed` with `Brave Browser 1.28.105 (Chromium: 92.0.4515.131)`.

**Comment by francislavoie** [comment]
Works fine for me. Ubuntu, Firefox, and also in Chrome 92.

Does your browser disable JS?

**Comment by 0x1a8510f2** [comment]
It does not, however, I've done a little more digging and it seems my user agent switcher extension breaks the site. That would explain why no one has reported this previously :P

It appears as though the page tries to pre-populate the platform box with the current platform and fails to recognise the user agent sent by the extension. This crashes the JS with the following error:

![image](https://user-images.githubusercontent.com/83190128/129256667-3a0411cc-70f7-4090-9373-5daee6a1fd56.png)

and, in turn, makes the page unusable.

Would you like me to keep this issue open or close it?

**Comment by mholt** [comment]
That's good to know -- we should fix that. (I'm a bit swamped today, want to submit a PR? :smile: ) Thanks for the report!

**Comment by 0x1a8510f2** [comment]
Sure, I can look into it. PR incoming :P

**Comment by francislavoie** [comment]
Oops, sorry @0x1a8510f2 I already made a PR :sweat_smile:

**Comment by 0x1a8510f2** [comment]
Ah, just when I set up my dev env. Good timing xP no worries though!

**Comment by mholt** [comment]
Thank you for contributing (both of you)!
