### ISSUE TITLE
reverse_proxy documentation issue saying "hostport" where "host" is correct

### ISSUE THREAD

**Issue by jrmyr** [caddyserver/website#188]
Hello,

I just figured out that the documentation has a minor issue:
It says
```
reverse_proxy localhost:9000 {
	header_up Host {http.reverse_proxy.upstream.hostport}
}
```
while
```
reverse_proxy localhost:9000 {
	header_up Host {http.reverse_proxy.upstream.host}
}
```
would be correct.
As caddy's log entries (level = deug) do not contain the host header actually sent to the upstream, this might cause confusion (and time loss) as it did for me. :-)

I wanted to push a branch to open a pull request but I lack the rights.

**Comment by francislavoie** [comment]
The former technically preserves more information, and it is valid. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host. It moreso depends on how your upstream app uses the `Host` header if at all.

> I wanted to push a branch to open a pull request but I lack the rights.

On Github, the way that works is that you need to make a fork of this repo, then make a branch on your fork. You can then open a PR from your fork's branch onto this repo.

But like I said earlier, I think the docs are correct as-is. Additional clarification could be added, but I don't think changing it from `hostport` to `host` is correct.

**Comment by mholt** [comment]
It depends on the backend. The docs aren't wrong, you just have to use what your backend requires.

Adding Host information to the logs sounds like a good idea though, if it isn't there already. I thought we log headers to the upstream though...

**Comment by jrmyr** [comment]
With concrete examples:
```
reverse_proxy https://example.com {
	header_up Host example.com
}
```
==> worked

```
reverse_proxy https://example.com {
	header_up Host {http.reverse_proxy.upstream.host}
}
```
==> worked

```
reverse_proxy https://example.com {
	header_up Host {http.reverse_proxy.upstream.hostport}
}
```
==> FAILED

So, I had to conclude that the hostport was wrong. Now, with your explanation I see that it might be right as it is. But then it would be very cool to get some additional info where the port is coming from. Or is it depending on the reverse_proxy protocol?

> It moreso depends on how your upstream app uses the Host header

Yeah, this might be my real issue. Thanks for pointing me to it.


> I thought we log headers to the upstream though...

The headers are in the log. But not the host header. I log on debug level and I can only see the host name under which the reverse proxy is running. But the host header used to do the request to the upstream is missing in the request header list. IMHO, it would be awesome to have it. But this is maybe not the topic of this ticket.

**Comment by francislavoie** [comment]
> Or is it depending on the reverse_proxy protocol?

Yeah, when you configure the proxy with `https://`, Caddy assumes port 443, because that's the usual HTTPS port. If you run `caddy adapt --pretty`, you'll see that the Caddyfile adapter transformed it into `"dial": "example.com:443"`, with `"tls": {}` to enable TLS.

**Comment by mholt** [comment]
The host is logged with the request, not as part of the headers. (Go pulls the Host header out for some reason.)

**Comment by jrmyr** [comment]
>  The host is logged with the request, not as part of the headers. 

I think that's not true. What is logged is the host under which the reverse-proxy is running; not the upstream host to which the reverse-proxy is forwarding. So you don't get the entire information what is sent to the upstream host. And I just say it would be great to have the entire information (at least in log mode debug).

**Comment by francislavoie** [comment]
Actually, the `request > host` in the logs is the mutated Host header.

While Caddy is doing work in the `reverse_proxy` module, `r.Host` is overwritten with the Host header actually being sent to the upstream, then gets reset back to its original value after `reverse_proxy` is done (via a `defer` closure) in case any subsequent request handlers in Caddy need the original Host value (leaving it mutated would leak some state).

The `"upstream roundtrip"` debug log has this information in it. It gets logged before the `defer` happens.

You can follow along in here:

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L365

- `reqHost := r.Host` saves the original value before proxying happens, and sets up a defer to reset it once proxying is done
- `h.Headers.Request.ApplyToRequest(r)` will apply any `header_up` mutation operations to the headers
- `h.reverseProxy()` does the work of actually proxying, and this is also when logging happens
- when `ServeHTTP` returns, the `defer` triggers

**Comment by jrmyr** [comment]
> Actually, the request > host in the logs is the mutated Host header.

That's not what I am experiencing. In detail:

I run caddy in Kubernetes (_caddy:2.4.1-alpine_)  with this Caddyfile content:
```
:8080 {
    reverse_proxy https://www.desthost.com {
        header_up Host {http.reverse_proxy.upstream.host}
        transport http {
            tls_client_auth /vault/secrets/desthost-client.crt /vault/secrets/desthost-client.key
            tls_server_name www.desthost.com
        }
    }
    log {
        output stdout
        format console {
            time_format iso8601
        }
        format filter {
            wrap console
            fields {
                request>headers>Authorization delete
            }
        }
        level debug
    }
}
```

A request produces this log (on the console):
```
1.6289574999485745e+09	info	http.log.access.log0	handled request	{
    "request": {
        "remote_addr": "127.0.0.1:59708",
        "proto": "HTTP/1.1",
        "method": "POST",
        "host": "desthost-proxy-service",
        "uri": "/some-path",
        "headers": {
            "User-Agent": [
                "ReactorNetty/0.7.6.RELEASE"
            ],
            "Accept": [
                "*/*"
            ],
            "Accept-Encoding": [
                "gzip"
            ],
            "Content-Type": [
                "application/x-www-form-urlencoded;charset=UTF-8"
            ],
            "Content-Length": [
                "271"
            ],
            "L5d-Dst-Canonical": [
                "desthost-proxy-service.my-namespace.svc.cluster.local:80"
            ]
        }
    },
    "common_log": "127.0.0.1 - - [14/Aug/2021:16:11:39 +0000] \"POST /some-path HTTP/1.1\" 200 911",
    "duration": 6.201317869,
    "size": 911,
    "status": 200,
    "resp_headers": {
        ...
    }
}
```
The `/var/log` dir is empty so I assume I get the full log.
As you see, the host field from the request is not the destination host the request is forwarded to (but the host name of the proxy container itself) and the host header is missing.

> The "upstream roundtrip" debug log has this information in it.

As you see, it does not contain it... There is just one log entry for the entire request handling.

Still, I say that it would be cool to have the real values as it would ease up debugging.
Describing me what the code does is not really helping when it does not provide what I would need for better debugging.
Or do I miss something and/or doing something wrong?

**Comment by mholt** [comment]
That is the access log only. The upstream roundtrip is in the regular debug level logs I believe. You might need to enable debug mode.

**Comment by francislavoie** [comment]
Those are _access logs_, not the `reverse_proxy` module's logs. The `log` directive (as in when you configure logs inside a site block) only produces access logs at the "server" level in Caddy, i.e. under the namespace `http.log.access`.

The logs I'm talking about are produced under the `http.handlers.reverse_proxy` namespace.

By default, those end up in Caddy's stdout. You can configure the `log` _global option_ to write them elsewhere, plus enable the `DEBUG` level logging to make `reverse_proxy` actually produce these logs. https://caddyserver.com/docs/caddyfile/options

**Comment by jrmyr** [comment]
I thought I did that (please see my config above): `level debug`.

Or is there another option I have to set?

**Comment by francislavoie** [comment]
You configured https://caddyserver.com/docs/caddyfile/directives/log which is _only access logs_. The `reverse_proxy` logs are not access logs.

**Comment by mholt** [comment]
Enabling debug level access logs doesn't do anything useful since currently there are no debug level access logs emitted. Enable debug mode in your Caddyfile instead, the reverse proxy logs are not access logs.

**Comment by jrmyr** [comment]
OK. I see. I will try that.
Thanks a lot for your rapid responses and detailed answers. And sorry I kept insisting on something I was misunderstanding.

**Comment by francislavoie** [comment]
No worries 👍
