### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by mafrosis** [caddyserver/website#192]
Hello, 

I'm currently getting an unhandled 500 from this incorrect URL:
https://caddyserver.com/docs/caddyfile/directives/errors

Please close if this issue is resolved by the time you read my message 😎

**Comment by francislavoie** [comment]
That's not a valid directive. The directive is `error`, not `errors`. https://caddyserver.com/docs/caddyfile/directives/error

Where did you get that URL from?

**Comment by mafrosis** [comment]
I typed the URL with my keyboard. I would expect a 404 and a friendly render?

**Comment by mholt** [comment]
We're not that sophisticated :laughing: 

But that is probably a better way to handle that. The website typically takes a backseat to actual Caddy development time.

**Comment by mafrosis** [comment]
All good, gents! Just thought you might be interested.. I was pretty sure I'd seen a pretty 404 page at some point, so this seemed like an edge case
