### ISSUE TITLE
Documentation Empty / 502

### ISSUE THREAD

**Issue by jjanyan** [caddyserver/website#194]
When I navigate to https://caddyserver.com/docs/json/apps/servers/tls_connection_policies/ the main content is empty.

Looking at the requests the page is making, I noticed a 502 to https://caddyserver.com/api/docs/config/apps/servers/tls_connection_policies/

**Comment by mholt** [comment]
I just noticed that... usually it takes a few seconds to load but 502 isn't right.

**Comment by mholt** [comment]
Oh, the correct link is https://caddyserver.com/docs/json/apps/http/servers/tls_connection_policies/ which works. 

I'm not sure how my link in the forum came to be https://caddyserver.com/docs/json/apps/servers/tls_connection_policies/. I wonder if the link parser did something funky and removed the `http/` from the middle of it or something.
