### ISSUE TITLE
Include example of matching a specific subdomain in reverse_proxy documentation 

### ISSUE THREAD

**Issue by simonw** [caddyserver/website#200]
This page has a bunch of useful examples: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

The one that was missing for me was one showing how to configure a reverse proxy such that traffic to a specific subdomain is routed to a specific backend - there's a path one but not one for a specific subdomain.

**Comment by mholt** [comment]
Hmm, I think what you're looking for is outside of just the scope of the reverse proxy, as the Caddyfile is structured entirely around hostnames, so:

```
sub.example.com

reverse_proxy ...
```

if you have one site/subdomain, or for multiple:

```
sub1.example.com {
    reverse_proxy ...
}
sub2.example.com {
    reverse_proxy ...
}
```

See the Caddyfile structure docs: https://caddyserver.com/docs/caddyfile/concepts#structure

**Comment by simonw** [comment]
OK that makes sense - so if I'm using a `Caddyfile` I would have set up the site domain at the root of the file.

I found an example of a subdomain match for the JSON API on this page: https://caddyserver.com/docs/quick-starts/https#json-config
