### ISSUE TITLE
Dead link: https://caddyserver.com/docs/caddyfile/directives/file_server

### ISSUE THREAD

**Issue by kashav** [caddyserver/website#201]
From https://caddyserver.com/docs/caddyfile/directives/file_server:

> <template_file> is an optional custom template file to use for directory listings. Defaults to the template that can be found [here in the source code](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/fileserver/browsetpl.go). Browse templates can use actions from [the standard templates module](https://caddyserver.com/docs/modules/http.handlers.templates#docs) as well.

That first link is dead. I'd submit a fix, but I can't figure out what the link was changed to.

**Comment by kashav** [comment]
Perhaps https://github.com/caddyserver/caddy/blob/3fe2c73dd04f7769a9d9673236cb94b79ac45659/modules/caddyhttp/fileserver/browse.html?

**Comment by francislavoie** [comment]
It's already been updated in this commit https://github.com/caddyserver/website/commit/b4f2b47adc03765e43a444ad7d53c329aa55d96d but hasn't been pushed live yet

**Comment by kashav** [comment]
Oh, great, thanks!

**Comment by mholt** [comment]
Yeah, sorry, will try to get around to it after the holidays.

**Comment by mqus** [comment]
Just found this ticket since I also stumbled on this (link is still dead), could you please reopen this issue, since it isn't fixed yet?

**Comment by mholt** [comment]
Updated
