### ISSUE TITLE
/api/docs/config/apps/auth responds with 502

### ISSUE THREAD

**Issue by stingalleman** [caddyserver/website#206]
Hi,

The API endpoint https://caddyserver.com/api/docs/config/apps/auth responds with a 502 error. This has been an issue since Nov 9 (https://github.com/abiosoft/caddy-json-schema/issues/7) and I decided to make an issue about it since it still hasn't been fixed. Guess nobody told the Caddy project.

I know this probably isn't the repository where this issue should be created, but the website didn't seem fitting to me and there wasn't an API repository.

**Comment by mholt** [comment]
Removed the auth plugin
