### ISSUE TITLE
includes/docs/ refactor suggest

### ISSUE THREAD

**Issue by fagci** [caddyserver/website#211]
In my practice, if files [named](https://github.com/caddyserver/website/tree/5f09f05e0825f0835691788699d32698faa55a54/src/includes) as `<prefix>-`, then subdirectory `<prefix>/` needeed.

Later, using `docs/` subdirectory you can load includes by category in organized way.

**Comment by mholt** [comment]
Sure. Would you like to make a pull request?

**Comment by fagci** [comment]
https://github.com/caddyserver/website/pull/212
