### ISSUE TITLE
map documentation could use some more information

### ISSUE THREAD

**Issue by brucejo75** [caddyserver/website#221]
Moved from https://github.com/caddyserver/caddy/issues/4642
<hr>

Did you know that the [map](https://caddyserver.com/docs/caddyfile/directives/map#map) directive cannot assign integers to placeholders? Unclear from the documentation. There is a lot of integer assignment in the example but if you assume the placeholder is an integer you would be wrong.

Luckily I ran across [this](https://caddy.community/t/maps-type-of-variables-and-expression/13994/2?u=brucejo) forum entry.

**Request**: please update the documentation to explain that the map directive cannot assign integers.

Thanks!

**Comment by brucejo75** [comment]
BTW: let me know if you would like me to submit a PR.  Happy to help!

**Comment by mholt** [comment]
The Caddyfile currently parses all values as strings. I suppose we could try to infer numbers and cast them before putting them into the `map` handler, but the `map` handler does in fact support numeric types if you use JSON.

I believe the only place the type of the map value would matter is in CEL expressions, not general Caddy usage.

**Comment by brucejo75** [comment]
That is a rather complicated specification.  Maybe worth some more documentation?  I am happy to take a shot at it if you like.

**Comment by mholt** [comment]
Well, I haven't tested it yet, but I pushed a quick fix here: https://github.com/caddyserver/caddy/commit/93c99f67342504efe9f6b58a734aaec3929fe785

It should now store numbers as numeric types (and booleans as booleans).

If you want to build from tip and test it out, that'd be splendid 😃

**Comment by francislavoie** [comment]
I had some ideas to make this nicer, and work "as expected" in more situations: https://github.com/caddyserver/caddy/pull/4643.

I liked Matt's idea of casting to scalar types, but it felt like a hack by doing it inside of the directive's parsing, instead of the token dispenser. And Matt's implementation didn't handle `"true"` and `"0"` as a strings, it would cast those to boolean/int respectively too.

**Comment by mholt** [comment]
Since that PR is merged, this should be much more intuitive now, which I think is more correct. Thanks!

**Comment by brucejo75** [comment]
Wow! OK
