### ISSUE TITLE
Beef up file_server precompressed documentation

### ISSUE THREAD

**Issue by brucejo75** [caddyserver/website#223]
Current documentation for [`file_server` `precompressed`](https://caddyserver.com/docs/caddyfile/directives/file_server#syntax):

> **precompressed** is the list of encoding formats to search for precompressed sidecar files. Arguments are an ordered list of encoding formats to search for precompressed [sidecar files](https://en.wikipedia.org/wiki/Sidecar_file). Supported formats are `gzip`, `zstd` and `br`.

Ambiguous elements of this documentation:
- What is a sidecar file?  This is the only place it is referenced in the caddy docs.
- What are the appropriate extensions for each compression?
- It is unclear that the uncompressed file needs to be in the root path in addition to the precompressed file.

Also, see https://caddy.community/t/solved-how-to-use-file-server-precompressed/15536.

Recommended change:

**precompressed** is the list of encoding formats to search for precompressed sidecar files. Arguments are an ordered list of encoding formats to search for precompressed sidecar files. Supported formats are `gzip`(`.gz`), `zstd`(`.zst`) and `br`(`.br`),

All file lookups will look for the existence of the uncompressed file first.  Once found Caddy will look for a sidecar file with a compression extension.  If a precompressed sidecar file is found Caddy will respond with the precompressed file and the response header will set the `content-encoding`  appropriately.  Otherwise Caddy will respond with the uncompressed file (and compress it on the fly if the `encode` directive is set).

**Comment by francislavoie** [comment]
If you want to make a pull request with your suggested changes, that'd be great! We can tune the wording during review 👍
