### ISSUE TITLE
`Module http.handlers.templates` page is badly rendered after the `import` section

### ISSUE THREAD

**Issue by davidbgk** [caddyserver/website#234]
Go to: https://caddyserver.com/docs/modules/http.handlers.templates

Scroll after the `import` section and:
<img width="905" alt="Capture d’écran, le 2022-05-13 à 09 39 59" src="https://user-images.githubusercontent.com/3556/168296118-beffed25-a7c6-49d6-85b7-cb2c3f9f2fd0.png">

The remaining of the page is affected.
I cannot find de related source for that page on the repository, I can make a merge-request if you guide me to the right file.

**Comment by francislavoie** [comment]
Thanks - it's been fixed in https://github.com/caddyserver/caddy/pull/4737 but not pushed live yet.

@mholt will get to it as soon as he can 🙂

**Comment by mholt** [comment]
Sorry, was out sick. Should be fixed now.
