### ISSUE TITLE
License of caddyserver.com/docs (for devdocs.io)?

### ISSUE THREAD

**Issue by simon04** [caddyserver/website#238]
Hi,

I'm a maintainer of https://github.com/freeCodeCamp/devdocs which combines multiple developer documentations in a clean and organized web UI with instant search, offline support. We require the docs [to be licensed under a free license](https://github.com/freeCodeCamp/devdocs/blob/main/.github/CONTRIBUTING.md#contributing-new-documentations).

Since Caddy is my favourite webserver, I'd love to have its docs included on https://devdocs.io/. How's the Caddy docs licensed? Is it compatible with devdocs' requirements?

Thanks!

**Comment by francislavoie** [comment]
Our docs have a bit of special sauce like some JS for adding links to code blocks, syntax highlighting provided by a Go lib included in Caddy itself, etc. And we already have search via algolia.

I think we'd generally rather users actually come to our docs for the best experience and for the most up to date docs. Single source of truth, etc.

**Comment by mholt** [comment]
That's awesome that you love Caddy, thanks for the comment and request!

But yeah, generally we try to aim everyone toward our official docs first, rather than other sites. A lot lot lot of problems are avoided when people do that.
