### ISSUE TITLE
caddyserver.com is down

### ISSUE THREAD

**Issue by kiwixz** [caddyserver/website#244]
Hello, https://caddyserver.com/ is down. I get "connection refused".

**Comment by eldonwilliams** [comment]
I thought it was just Safari being stupid, but no. I tried it on Chrome on my main PC and had the same issues. Is this related to the Twitter outage? I'm willing to bet they use the same provider.

**Comment by francislavoie** [comment]
It's back up, @mholt rebooted it. Digitalocean has been flaky lately. 😬

**Comment by mholt** [comment]
So. Yeah, it's true that DO [has been flaky lately](https://caddy.community/t/caddys-download-api-server-is-not-responding/16177/6?u=matt).

But in this case, it looks like our disk reads and outbound bandwidth spiked to 200 MB/sec.

Logs show a _huge_ influx of requests for the homepage (`/`) minutes before the server just... stopped. It choked? I dunno. The logs show a bajillion connections from `5.135.36.100` with User-Agent `axios/0.26.1`. This time it seems to be a classic DoS. 🤷‍♂️
