### ISSUE TITLE
Caddy website down?

### ISSUE THREAD

**Issue by weakcamel** [caddyserver/website#245]
Sorry for raising this here but I've no idea where else I could.

caddyserver.com is down so no downloads or documentation etc etc.

Hope it's just temporary and not a big deal!

**Comment by francislavoie** [comment]
We've been having issues with DoS and our hosting provider lately :grimacing: https://github.com/caddyserver/caddy/issues/4857

It is temporary, @mholt will need to reboot it as soon as he can.

For now you can find the docs here https://github.com/caddyserver/website/tree/master/src

If you need to download Caddy, either grab it from the github releases tab, or build from source yourself with `xcaddy` https://github.com/caddyserver/xcaddy

**Comment by mholt** [comment]
Again??

It appears to be the same issue as https://github.com/caddyserver/website/issues/244 -- but even a higher flood of requests, from the same IP: `5.135.36.100`

**Comment by weakcamel** [comment]
Thanks for the instantaneous reply!

I'm installing Caddy with Ansible (https://github.com/caddy-ansible/caddy-ansible) which picks builds up from the website but it's fine. I can just temporarily disable that part.

Fingers crossed your problems get resolved soon.

**Comment by francislavoie** [comment]
I really wish it didn't do that. That adds pressure to the website. It should build from source with `xcaddy` or pull from github. Automated tooling should _not_ hit the website.

**Comment by weakcamel** [comment]
@francislavoie I was trying to connect the dots here and raised https://github.com/caddy-ansible/caddy-ansible/issues/45

I can relate to the answer from @joelnb though - Ansible is a great tool for deployments but it doesn't have any capabilities of setting up a build environment and even if that were feasible, this means  it would need to be set up on the host to be running Caddy (you can run Ansible from e.g. MacOS against a Linux box) - which is usually not practical, that target host doesn't usually have Golang compiler installed and for good reasons.
