### ISSUE TITLE
The `JSON structure` link on this page goes to a 404

### ISSUE THREAD

**Issue by geoidesic** [caddyserver/website#248]
[JSON structure](https://github.com/caddyserver/website/blob/master/docs/json)
<img width="1091" alt="Screenshot 2022-07-18 at 22 02 32" src="https://user-images.githubusercontent.com/4637995/179616848-bc00a554-1757-4c11-b686-54006558265e.png">

**Comment by mholt** [comment]
Works for me :thinking: 

What is the link for you?

It should be https://caddyserver.com/docs/json/.

Please post the output of `curl -v "https://caddyserver.com/docs/json/"`

**Comment by geoidesic** [comment]
I guess I'm misunderstanding how to access the docs? I was on this page: https://github.com/caddyserver/website/blob/master/src/docs/markdown/getting-started.md and the `JSON structure` link on that page goes to a 404

**Comment by mholt** [comment]
Huh? That's just a markdown rendering of the file in our dev repo. The docs are on our website: https://caddyserver.com/docs/.
