### ISSUE TITLE
HTTP/3: "Client support is extremely limited."

### ISSUE THREAD

**Issue by appliedprivacy** [caddyserver/website#256]
When editing this line in 
https://github.com/caddyserver/website/pull/255/files

we were wondering whether this is about caddy's HTTP/3 client support (when doing outbound requests) or HTTP clients in general, like browsers?

If it is about HTTP clients in general, it should be updated to reflect that most major browsers have HTTP/3 support by now.
https://en.wikipedia.org/wiki/HTTP/3#Browser

**Comment by mholt** [comment]
Yes we are updating this for Caddy 2.6 which is coming soon!
