### ISSUE TITLE
Typo in map directive docs

### ISSUE THREAD

**Issue by brucejo75** [caddyserver/website#258]
Typo in docs [here](https://caddyserver.com/docs/caddyfile/directives/map#examples), discovered in caddyserver/caddy#4987.

this example:
> 	`(.*)\.example.com  "${1} subdomain"  5`

should be changed to 
> 	`(.*)\.example\.com$  "${1} subdomain"  5`

Although, `(.*)\.example.com` will match `something.example.com` it will also match `something.exampleXcom` (or any other character for the last `.`) & it will match  `something.example.com.foo.bar` because the regular expression does not specify the end of string.

> 	`(.*)\.example\.com$  "${1} subdomain"  5`

I believe conveys the intent more accurately.

**Comment by francislavoie** [comment]
I transferred the issue to the website repo, which is where the website's source is.

Feel free to open a pull request to make the changes you propose!

**Comment by mholt** [comment]
Thanks! I went ahead and fixed it. Also added `~` since it's a regex...
