### ISSUE TITLE
Global option: log include/exclude value are difficult to find

### ISSUE THREAD

**Issue by Jiehong** [caddyserver/website#260]
Hi everyone,

I couldn't find some info in the doc, so I'm opening a ticket.

## Problem

When you want to configure the global log, you basically go to https://caddyserver.com/docs/caddyfile/options#log.

It does speak about the include/exclude: 

> For example, to include only logs emitted by the admin API, you would include admin.api.

But you then have no idea what are the possible values.

Looking further I was able to find this page: https://caddyserver.com/docs/extending-caddy/namespaces

But it doesn't reference all modules, since the example one is not there.

Looking even further in https://caddyserver.com/docs/logging#logging-pipeline, we have a similar clue:

> Each message is emitted by a logger, which has a name (usually derived from the module ID). Logs can include or exclude messages from certain loggers.

Still unclear what exactly can be set there.

Going to the json field doc, for example https://caddyserver.com/docs/json/logging/logs/include/, gives nothing more.

Nor does https://caddyserver.com/docs/json/logging/logs/#include hint at a better thing.

(In the end, I only found about `http.log` namespace via https://caddy.community/t/log-reverse-proxy-upstream/8610/2)

## Expected

As a user of Caddyfile, I would expect 2 things for this particular log.include and log.exclude global option:

1. an actual example in caddyfile format, such as (to log access logs, error logs, and admin api logs):

```sh
include http.log admin.api
```

2. A link to a list of all default namespaces (so the [the contexnt of this](https://caddyserver.com/docs/extending-caddy/namespaces), plus the missing ones, such as http.log, admin.api, etc.).

**Comment by mholt** [comment]
It's true we don't have this really well documented, but it would be very tedious to maintain that documentation.

Loggers are named by their modules (if coming from a module), or from a word that describes which part of Caddy, like `admin`.

I think the best way to determine which logs you want to include or exclude is to get the name from the log entries themselves! :+1:

**Comment by Jiehong** [comment]
@mholt : I can understand that, but not everything is logged by default (the default value of include/exclude is not documented either).

For example, I wanted to log the things from the reverse proxy, but also the errors, but the log directive only showed the access logs, but not the error logs, and the reverse_proxy handler doesn't seem to do anything.

I only stumble by accident on `http.log` by removing part of the name itself (instead of `http.log.access.log0` found in that community link).

So, how about documenting the following instead?

- The default value of include/exclude
- What value to set so that _every logger_ is logged (I have no idea how to do that), and tell the user to adapt the values by selecting the `logger` value wanted.
- Show an example

**Comment by mholt** [comment]
@Jiehong True:

> the default value of include/exclude is not documented either

I'll clarify this in the docs. By default, all logs are included in a logger.

> For example, I wanted to log the things from the reverse proxy, but also the errors, but the log directive only showed the access logs, but not the error logs, and the reverse_proxy handler doesn't seem to do anything.

Then it sounds like the reverse_proxy handler isn't even being invoked if it's not doing anything at all. Most of its logs are at the DEBUG level, so make sure you enable that if you're troubleshooting.

> Show an example

Of what, exactly?

**Comment by francislavoie** [comment]
> I'll clarify this in the docs. By default, all logs are included in a logger.

Should be noted; access logs are turned off by default, so they won't appear until you enable them per-site with the `log` directive (which is different than the `log` global options, even though they share almost the same settings).

**Comment by Jiehong** [comment]
@mholt 
> Of what, exactly?

Just an example in caddyfile format for include/exclude

> I'll clarify this in the docs. By default, all logs are included in a logger.

I meant what is the default list of values for include and for exclude, but not what a single logger logs.

Together, the default values can be the example, aka something like this:

```
By default, caddy uses the following values:
include admin.api
exclude http.log.access http.log.error
```

(idk the real default values)

**Comment by mholt** [comment]
> Just an example in caddyfile format for include/exclude

So, like this?

```
log default {
	exclude http.log
}
```

I don't really get the value of this though. :man_shrugging: It's pretty clear from the syntax, yeah?

```
exclude <namespaces...>
```

> I meant what is the default list of values for include and for exclude, but not what a single logger logs.

The default list of values for those parameters is empty.

**Comment by Jiehong** [comment]
I propose a PR to fix it: https://github.com/caddyserver/website/pull/262
