### ISSUE TITLE
Upcoming features section on v2 product page outdated

### ISSUE THREAD

**Issue by Klooven** [caddyserver/website#269]
Hi, I just read that you've released Caddy v2.6! Congratulations and thank you for the great work @mholt and everyone else -- I can't wait to try out the new features.

Just as a heads-up, when going to Caddy v2's product page on https://caddyserver.com/v2 there's an outdated section on the bottom:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/12278148/191356999-f685a539-351e-4783-b0b2-9314384b5030.png">

This should probably be updated at some point. An easy "do it and forget it" way to accomplish that could be to simply link to Caddy's pull requests page on GitHub. But maybe someone else has a better imagination when it comes to refactoring the section 🤔

**Comment by mholt** [comment]
We have a website?

Oh, right :sweat_smile: 

I guess we should update it at some point... I like the idea of linking to the PRs. Or maybe we can put our recent tweets there (and change it from "There's more around the corner" to something else)

**Comment by Klooven** [comment]
A Twitter feed sounds like a good idea, too. I could open a PR to replace the content of the section with the feed, if that's ok 😄

**Comment by mholt** [comment]
I'm designing a new website to hopefully launch this year (FYI).

**Comment by Klooven** [comment]
@mholt Hi, sorry – I forgot this issue totally! Would you still be interested in a PR to fix this issue or should we let this be and let the website redesign "resolve" it?

**Comment by mholt** [comment]
No worries 🙂

I probably won't be putting effort into the current site (except to fix major bugs or something) since the redesign will completely replace it 👍

**Comment by Klooven** [comment]
Closing this as resolved 🙂 (the redesigned sections of the website look good!)

**Comment by mholt** [comment]
Oh I forgot about this. Thank you!
