### ISSUE TITLE
Broken Page

### ISSUE THREAD

**Issue by AnTheMaker** [caddyserver/website#278]
Hi there!
It seems like the following page is broken: https://caddyserver.com/docs/modules/http.handlers.templates
The entire "Description" section is missing which makes **a lot of important content** inacessible.
See this archived version for a reference on how it should be: https://web.archive.org/web/20220714024327/https://caddyserver.com/docs/modules/http.handlers.templates

Love Caddy btw - keep up the great work!

**Comment by francislavoie** [comment]
Known issue. Will be fixed with the release of v2.6.3 https://github.com/caddyserver/caddy/commit/1cd594963eb54b011764e1172b18aabd3bde90d3

Sorry about that!

**Comment by AnTheMaker** [comment]
Awesome, thanks for the quick reply!
