### ISSUE TITLE
The website isn't building customized Caddy versions

### ISSUE THREAD

**Issue by flavorgold1** [caddyserver/website#298]
https://caddyserver.com/download?package=github.com%2Fmholt%2Fcaddy-webdav&package=github.com%2Fcaddy-dns%2Fcloudflare&package=github.com%2Fcaddy-dns%2Fduckdns&package=github.com%2Fmholt%2Fcaddy-dynamicdns

That doesn't get me what I'm looking for.

It just stays stuck on building.

**Comment by mholt** [comment]
Sigh, looks like the `go get` bug again (it's been stuck for 12 hours) -- I really wish Go would fix it, but I don't know how to report any meaningful information to them to reproduce it.

I rebooted the build server. If it happens again, try building with one fewer plugin each time until it works. Once it does, let me know which plugin caused it to start working (that's the one that made it break).
