### ISSUE TITLE
new site is skiddywompus on Chrome on Mac

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/website#3]
![screen shot 2017-04-21 at 11 53 32 am](https://cloud.githubusercontent.com/assets/122831/25290046/6ea0c236-2689-11e7-925e-5ca97b76c062.png)
![screen shot 2017-04-21 at 11 53 56 am](https://cloud.githubusercontent.com/assets/122831/25290045/6ea0fc74-2689-11e7-954e-56329badd8b8.png)
![screen shot 2017-04-21 at 11 54 03 am](https://cloud.githubusercontent.com/assets/122831/25290048/6eb57640-2689-11e7-84b4-f47c00df92ab.png)
![screen shot 2017-04-21 at 11 54 14 am](https://cloud.githubusercontent.com/assets/122831/25290047/6eb47560-2689-11e7-88c3-b84461035255.png)

**Comment by coolaj86** [comment]
Some of it may have been application cache or something... which I have no idea how I would have...

**Comment by mholt** [comment]
I forgot about caches when I updated the site, sorry. Clearing your cache should make it look nice. Thanks for the question!

**Comment by coolaj86** [comment]
For the record: I like the old font and logo and background better. They were much easier on the eyes. This one is very noisey (literally those wavey shapes are the definition of noise) and the super-bold low-contrast font of the name "caddy" is harder to parse.

I've also have had a few people tell me they think I might have aspergers and that sign on I-15 with the image and text "Sensory Overload is a sign of autism" with all the crazy waves and shapes or whatever it is drives me insane (I can't stand to look at it) so... take that for what it's worth.
