### ISSUE TITLE
Unable to register new module

### ISSUE THREAD

**Issue by fvbommel** [caddyserver/website#304]
While attempting to register a new [IP source for `trusted_proxies`](https://caddyserver.com/docs/json/apps/http/servers/trusted_proxies/), I got the following error message:

> ### Internal Server Error
>
> Sorry, something went wrong:
>
>unable to scan modules in package github.com/fvbommel/caddy-dns-ip-range
>
> Please include this error ID if reporting:  
> b63bd9f4-d2bc-4436-88ff-0a4e20a5a49a

**Comment by mohammed90** [comment]
The error message in our logs says:
> expect either composite literal or new()

You can remove the `&` to register a value (non-pointer) or use `new(DNSRange)`.

**Comment by fvbommel** [comment]
I don't want to make it a non-pointer because it contains a sync.Mutex. I know it doesn't matter in this case because it won't actually be used, but I don't want to see the yellow squiggle in the code because I'm passing a Mutex by value.

I changed it to `new(DNSRange)`, but still get the same error:

> ### Internal Server Error
> 
> Sorry, something went wrong:
> 
> unable to scan modules in package github.com/fvbommel/caddy-dns-ip-range
> 
> Please include this error ID if reporting:  
> d8546269-7f9e-4f24-8323-afe36e311ebd

**Comment by mohammed90** [comment]
Sorry :sweat: The portal is using cached version. Use `latest` or `master` or the latest version of your package in the `version` field.
Apologies for the recurring pain. We do have the improvements on our roadmap.

**Comment by fvbommel** [comment]
"latest" did it, thanks.
