### ISSUE TITLE
Can not build and download from homepage

### ISSUE THREAD

**Issue by Kani3D** [caddyserver/website#307]
Hello,

first of all thanks for this!
I'm currently having issues to build and download this: (Linux amd64)
https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fduckdns
Tried different browsers, different networks.

Thanks in advance.

**Comment by mholt** [comment]
This is due to a bug in the Go command: https://github.com/golang/go/issues/53905

Duplicate of #306, #300, #298 ...
