### ISSUE TITLE
Ubuntu/Debian/Raspbian install instructions not working anymore

### ISSUE THREAD

**Issue by chr1st0ph3rGG** [caddyserver/website#311]
Not sure if this is the right place but since these instructions can be found in this repo I give it a shot here...

Tried to use the install instructions on the website for a RaspberryPi setup and failed: 

I used the https://github.com/caddyserver/website/blob/master/src/docs/markdown/install.md instructions for Ubuntu/Debian/Raspbian

Specifically the `curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list` part is the problem, because cloudsmith does not provide the requested file there anymore (we still get the gpg key )... same problem occures for the testing branch...

**Comment by francislavoie** [comment]
That file looks fine to me. I think cloudsmith just had an outage https://status.cloudsmith.io/
