### ISSUE TITLE
How to add moudle in  download-page  ？

### ISSUE THREAD

**Issue by zuohuadong** [caddyserver/website#316]
When I install "https://github.com/greenpau/caddy-git" ,  it appears: 

![image](https://user-images.githubusercontent.com/11203929/233225736-92200891-8018-4b37-92d4-4f74c1cc5593.png)

And this project hasn't had a PR merge for a long time.

I want to add my module, how do I add it?

see：

https://github.com/zuohuadong/caddy-git

**Comment by mholt** [comment]
This is a known problem, unfortunately. We have workarounds.

But I'm wondering why the big red banner explaining this is not showing for you?

![image](https://user-images.githubusercontent.com/1128849/233252998-def63655-73ae-44ce-84e5-711ebd25a6f0.png)

Make sure your cache is clear? (But we've had the banner for a long time now.)

Anyway, duplicate of #308, https://github.com/caddyserver/website/issues/307, https://github.com/caddyserver/website/issues/306, https://github.com/caddyserver/website/issues/300, https://github.com/caddyserver/website/issues/298 ...

**Comment by francislavoie** [comment]
You can make an account to claim your package.

But I strongly recommend not doing it for forks, because it can be especially confusing for users to see multiple versions of the same package. Best if you have some patience for the maintainer to merge the fixes (or get them to add someone else as a maintainer to help).

FYI @greenpau

**Comment by greenpau** [comment]
I will update it. Hopefully tomorrow.

**Comment by zuohuadong** [comment]
@mholt 

Unfortunately, compiling yourself with xcaddy does not solve the problem, and you get an error similar to the following：

![image](https://user-images.githubusercontent.com/11203929/233303816-ab1725cc-97fa-400f-9cc5-7fe3ec13696a.png)


Why can't you try it yourself before making a decision?

The good news is that this PR solved the problem, but it was delayed to merge：

https://github.com/greenpau/caddy-git/pull/20

So, this is essentially a matter of maintainers not merging, I guess originally wanted to replace greenpau's project and build a new one, but the good news is, he's back.



Keep up the kindness, thanks.

**Comment by francislavoie** [comment]
> Why can't you try it yourself before making a decision?

He didn't "make a decision". It is a fact that these build problems complaining about `pprof` have to do with a bug in Go stdlib, as mentioned in the various issues he linked. These errors have nothing to do with the Caddy website, so there's no reason to keep the issue open.

**Comment by zuohuadong** [comment]
> > Why can't you try it yourself before making a decision?
> 
> He didn't "make a decision". It is a fact that these build problems complaining about have to do with a bug in Go stdlib, as mentioned in the various issues he linked. These errors have nothing to do with the Caddy website, so there's no reason to keep the issue open.`pprof`

Thanks.
In fact, I certainly saw that banner, but it was clear that it didn't solve anything.
I mean: the original purpose of asking this question was to maintain caddy git yourself. It's so bad that you can't build it with xcaddy.

**Comment by mholt** [comment]
Yes, we too are frustrated that the `go` command is broken. There's not much we can do about that.

**Comment by mohammed90** [comment]
> It's so bad that you can't build it with xcaddy.

Sure you can. You can use this command:

```
xcaddy build     --with github.com/greenpau/caddy-git=github.com/zuohuadong/caddy-git@v1.0.8
```

You've shared that exact command on another thread. It works.

**Comment by greenpau** [comment]
Release https://github.com/greenpau/caddy-git/releases/tag/v1.0.8
