### ISSUE TITLE
Description for grace_period in caddyfile and json config documentation differs

### ISSUE THREAD

**Issue by Xerkus** [caddyserver/website#319]
https://caddyserver.com/docs/json/apps/http/#grace_period
Json config documentation describes grace_period as such:

>    GracePeriod is how long to wait for active connections when shutting down the servers. During the grace period, no new connections are accepted, idle connections are closed, and active connections will be given the full length of time to become idle and close. Once the grace period is over, connections will be forcefully closed. If zero, the grace period is eternal. Default: 0.
>
>    Duration can be an integer or a string. An integer is interpreted as nanoseconds. If a string, it is a Go time.Duration value such as 300ms, 1.5h, or 2h45m; valid units are ns, us/µs, ms, s, m, h, and d.

https://caddyserver.com/docs/caddyfile/options#grace-period
While caddyfile describes it as:
> Defines the grace period for shutting down HTTP servers during config changes. During the grace period, no new connections are accepted, idle connections are closed, and active connections are impatiently waited upon to finish their requests. If clients do not finish their requests within the grace period, the server will be forcefully terminated to allow the reload to complete and free up resources. By default, no grace period is set.

Since caddyfile is an adapter for json I assume caddyfile description is simply out of date and grace_period in caddyfile would apply to server shutting down as well as accept same values as json.

**Comment by mholt** [comment]
Oh, you're referring specifically to the omission of duration units in the Caddyfile docs?

We actually do describe them on this page to avoid repetition: https://caddyserver.com/docs/conventions#durations

Maybe we could add a link to that section. Want to submit a PR?

**Comment by francislavoie** [comment]
We typically add a mention like `Accepts [duration values](/docs/conventions#durations)`

**Comment by Xerkus** [comment]
I was referring more to the "during config changes" actually as I was looking for a grace period for shutting the server down when container is stopping. 

Caddyfile docs imply it will only affect reload and not outright stopping server on SIGINT as well as that connections will be terminated immediately.

Mention of units is nice to have but these are covered elsewhere.

**Comment by francislavoie** [comment]
:point_up: made a commit to improve it. Make sense?

**Comment by Xerkus** [comment]
Json suggests default is to wait forever. 
>  If zero, the grace period is eternal. Default: 0.

**Comment by francislavoie** [comment]
You're right :man_facepalming: sorry

**Comment by Xerkus** [comment]
Had to test.
Setting to `0` or `0s` does make it wait forever. It is not intuitive, so I think it should be mentioned explicitly.

**Comment by francislavoie** [comment]
Is that last commit not clear? I think it is.

Either way, I think the default is bad. We might adjust it in a future release (to set a sensible upper limit, like maybe 10 or 30 seconds), we just need to do a bit more investigating first.

**Comment by Xerkus** [comment]
It is clear.
I don't think anyone would try to disable grace period entirely so 0 does not matter.

Feels weird to review as contributor changes from maintainer.
Do I get to say "thank you" and merge the PR at the end too? :laughing:

**Comment by francislavoie** [comment]
We maintain Caddy, but we don't use it in every possible way, because the usecases are infinite. So we need to trust that users will help point out problems for their own usecases, as you have.

I forgot the specifics of how `grace_period` works because I never really need it myself; I don't tend to use Caddy with apps that have lots of long-running connections, except for websockets which we have special handling for to immediately close; we're making changes for that soon as well.

But reconsidering it with what I know now, I think the default is not good and that we should set it to something sensible like I said. If users actually do want it to be eternal (which would be surprising/weird IMO) they could just set it to something crazy like `grace_period 1d` (1 day)

**Comment by Xerkus** [comment]
I agree. 
There are cases for long lasting connections like serving large file over slow network and such but it would be a pretty rare case where it matters for shutdown timeout.

ECS has 30 seconds default shutdown timeout iirc. HashiCorp Nomad has default maximum timeout at 30 seconds. It wouldn't be unreasonable for http server.

This issue was resolved so I am going to close it now. Thanks.

**Comment by francislavoie** [comment]
Yep, Docker has a default 10s grace as well (SIGINT right away then SIGTERM 10s later).
