### ISSUE TITLE
Revamp UI for Code Snippets on Website

### ISSUE THREAD

**Issue by Shriansh2002** [caddyserver/website#327]
**Issue Description:**
Currently, the code snippets displayed on the website have a dull and unappealing user interface. This issue aims to revamp the UI of the code snippets, making them visually engaging and user-friendly.

<img width="1092" alt="Screenshot 2023-06-08 at 9 15 56 AM" src="https://github.com/caddyserver/website/assets/41548480/1a523c44-d95a-4ad3-a20f-1875a575eae1">

To address this issue, we need to update the UI of the code snippets on the website.

I would be happy to work on working on this revamping.

**Comment by mholt** [comment]
I'm open to this, but can you post images of what it would look like first?

What you posted an image of is not a code snippet, btw. It's a command for a terminal, and terminals usually look something like that.

FYI: I'm currently redesigning our website as a whole -- new docs too -- so ideas from this could likely make it into the new site.

**Comment by mholt** [comment]
Did you mean to close this?

**Comment by Shriansh2002** [comment]
In React and NextJS applications, I typically utilize the react-syntax-highlighter library along with lowlight to create code blocks. This approach simplifies the process within React applications. However, I understand that you are seeking on implementing code blocks using pure HTML, CSS, and vanilla JS.

So it would be easy to do so in the react application, but I do not have any idea of implementing it in the pure html, css and vanillaJS.

Snippet which I wanted to share.
<img width="489" alt="Screenshot 2023-06-20 at 10 16 25 PM" src="https://github.com/caddyserver/website/assets/41548480/e0192203-8a6a-426e-879e-534118fe5ccc">

**Comment by mholt** [comment]
Ok, thanks. Yeah, we are a pretty vanilla front-end shop here. But we do highlight code snippets already on the server-side.

Will close then, since there's not really anything actionable at the moment.
