### ISSUE TITLE
Change client_ip to remote_ip in matcher API docs

### ISSUE THREAD

**Issue by SteffeyDev** [caddyserver/website#328]
[This page in the docs](https://caddyserver.com/docs/json/apps/http/servers/routes/match/client_ip/) says to use `client_ip` as the matcher key, but I discovered that I actually needed to use `remote_ip`, as using `client_ip` resulted in:
```
{"error":"loading config: loading new config: loading http app module: provision http: server srv0: setting up route matchers: route 4: loading matcher modules: module name 'client_ip': unknown module: http.matchers.client_ip"}
```
Is this an error in the docs?

**Comment by mholt** [comment]
It's a recent addition. Are you using the latest Caddy version?

**Comment by SteffeyDev** [comment]
I may not be, if that’s the case then we can close!

**Comment by SteffeyDev** [comment]
Was it simply renamed in the latest version?

**Comment by SteffeyDev** [comment]
Ah I see now, both are available

**Comment by francislavoie** [comment]
The purpose of the client_ip matcher is to use the IP address from the X-Forwarded-For header if `trusted_proxies` is configured on the server. It's only useful if you have another proxy in front of Caddy. If you don't, then you should continue using the remote_ip matcher which exclusively reads from the IP address on the TCP packets.
