### ISSUE TITLE
Idea: host on hertzner

### ISSUE THREAD

**Issue by gedw99** [caddyserver/website#329]
i saw there were issues with digital domain in the past.

its just me but i find hetzner much easier to host on.

their robot will provision a dedicated server and you can run docker and the web site, etc

https://github.com/woodpecker-ci/woodpecker is the CI system. 

https://github.com/woodpecker-ci/autoscaler has the robot code so the CI system can create a server and scale them up and down.

its working well for me.

**Comment by mholt** [comment]
Thanks, we'll consider it!

(Closing, as nothing actionable at this point, but will refer to this issue if we decide to relocate infrastructure.)

**Comment by mohammed90** [comment]
To clarify, our pain points aren't with the hosting provider as much as it's how the infrastructure is setup and its components interact with each other.
