### ISSUE TITLE
api endpoint code

### ISSUE THREAD

**Issue by gedw99** [caddyserver/website#330]
The code in this repo expects an **API** endpoint. 

It seems to do login, etc. can you let me know where that is.

/api/create-account

**Comment by mholt** [comment]
Our website backend is a Caddy plugin, but it's not a public repo.

**Comment by gedw99** [comment]
Ok thanks for letting me know.

I way to work on a passkeys module for caddy . Hats why I was curious.

**Comment by gedw99** [comment]
https://github.com/teamhanko/hanko/issues/868

**Comment by mholt** [comment]
I'd love to support passkeys as a caddy plugin, and for our site. If I invite you to our developer Slack is this something you'd like to build?

**Comment by gedw99** [comment]
Great !! 

Yes please invite me .

I have some time at the moment. 

Do you need my email ?

Thanks @mholt

**Comment by mholt** [comment]
@gedw99 Yes that would be helpful :)

**Comment by mholt** [comment]
Closing due to nothing actionable here... if you want an invite to our Slack though just let me know your email address.
