### ISSUE TITLE
Consider not recommending less secure and privacy friendly Referrer-Policy setting

### ISSUE THREAD

**Issue by hannob** [caddyserver/website#344]
The docs for the header directive here contain recommendations / examples for the Referrer-Policy setting:
* https://caddyserver.com/docs/caddyfile/directives/header
* https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/directives/header.md

The example sets Referrer-Policy to "no-referrer-when-downgrade". Current browser defaults are more strict, see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

The default in modern browsers is "strict-origin-when-cross-origin", which means not sending a path and potential GET variables when clicking a link going to another host / origin.

This is more privacy friendly (less information leaked to a third party), and can also prevent potential security issues if there are variables or other information in the URL. I would either recommend to not have that in the examples or set it to browser's defaults.

**Comment by francislavoie** [comment]
I wouldn't call those recommendations. We specifically have a warning there saying not to use it unless you understand the implications. It's just an example.

That said I'm fine with removing that header from the example, I agree it's worse than the default. PR is welcome

**Comment by mholt** [comment]
Yeah we can remove that one. I'll take care of that soon. Thanks
