### ISSUE TITLE
HTTP 500 at https://caddyserver.com/docs/faq

### ISSUE THREAD

**Issue by polybuildr** [caddyserver/website#35]
Hello! I followed a (probably outdated) link from an old issue to https://caddyserver.com/docs/faq and got back an HTTP 500. Assuming the page doesn't exist anymore, the response needs to be fixed to be a 404.

**Comment by mholt** [comment]
Yeah, that's because our docs are templated from Markdown files, so if the URL isn't right, the templates don't parse succesfully, so you get a 500 instead of a 404.

This can probably be improved but it's not a priority right now.

**Comment by polybuildr** [comment]
Ah, I see. Thanks for your work on Caddy! :) And sorry for filing this in the wrong repo.
