### ISSUE TITLE
Docs: Mention which log levels are possible

### ISSUE THREAD

**Issue by steffenbusch** [caddyserver/website#351]
Coming from the "Java world" with `java.util.logging` and `log4j`, it is not clear to me which log levels are supported or what their correct names are.

On https://caddyserver.com/docs/caddyfile/options#log it says:
> level is the minimum entry level to log. Default: `INFO`.

It would be nice, if the names of the other possible log levels could be added. 
(Especially if it's WARN or WARNING or something else).

**Comment by mholt** [comment]
Ah yeah, that would be a good idea. Will do that.

**Comment by francislavoie** [comment]
I'll also add a note that for access logging we only use info and error currently. Log levels are only mostly useful for runtime logs ultimately.
