### ISSUE TITLE
`path_regexp` documentation in "Request matchers" is incorrect about placeholders

### ISSUE THREAD

**Issue by tgeoghegan** [caddyserver/website#353]
I can find two pieces of documentation for the `path_regexp` matcher. The first is [here](https://caddyserver.com/docs/caddyfile/matchers#path-regexp) and it discusses placeholders:

> Capture groups can be accessed via [placeholder](https://caddyserver.com/docs/caddyfile/concepts#placeholders) like {re.name.capture_group} where name is the name of the regular expression (optional, but recommended) and capture_group is either the name or number of the capture group in the expression.

But this is incorrect: with Caddy 2.7.5, I found that I had to use the placeholder `{http.regexp.name.capture_group}`. That documentation appears to be in this project  ([source](https://github.com/caddyserver/website/blob/8a9540d4ecd6e5ed82d773742ad6d400f4570646/src/docs/markdown/caddyfile/matchers.md?plain=1#L576)) so I filed an issue here.

There's also documentation specific to the `path_regexp` plugin [here](https://caddyserver.com/docs/modules/http.matchers.path_regexp), and it uses the correct placeholder name.

**Comment by francislavoie** [comment]
No, it's correct. It's a Caddyfile shortcut: https://caddyserver.com/docs/caddyfile/concepts#placeholders `{re.*.*}` becomes `{http.regexp.*.*}` when the Caddyfile is adapted to JSON.

**Comment by tgeoghegan** [comment]
I think I see what happened: I am providing my config as JSON, and in that setting, using `{re.*.*}` doesn't work because no Caddyfile -> JSON translation occurs. This is working as intended and since the documentation I was complaining about is clearly in the "Caddyfile" section, I can see the argument for that being correct.

Nonetheless, I did find this confusing. I don't have a concrete suggestion for how to improve it, though.

**Comment by mholt** [comment]
I'll see if maybe we can clarify this in the refreshed docs next year.
