### ISSUE TITLE
Claim for support of ‘Static site using database as file system’ is false advertising

### ISSUE THREAD

**Issue by dpk** [caddyserver/website#359]
<https://caddyserver.com/#file-server> claims (emphasis mine):

> Serve your static site from anything: the local file system, remote cloud storage, a *database, or even embedded in the server binary!*

With the example

```
# Static site using database as file system
file_server /database/* {
	fs sqlite data.sql 
}
```

Curious, I tried to find more information on how to do this — what schema the SQLite database should have, etc.

There is no Google result other than the caddyserver.com home page for `[caddy "fs sqlite"]`. There appears to be no `fs.sqlite` module available from ZeroSSL or any affiliated company or third party. I could find no other relevant results with Google, DuckDuckGo, nor with GitHub search showing how this feature is concretely supported by Caddy.  Similar considerations appear to apply to the `fs embedded` example following it, although I haven‘t looked extensively.

As such, this claim appears to be false advertising. At most, it appears to me that Caddy could claim to support a SQLite `fs` module *in theory*, if someone wrote the code for it. The current website states that this is possible as a feature of Caddy itself, which is not true.

**Comment by mholt** [comment]
Is this something you are needing?

**Comment by dpk** [comment]
I’m currently working on a static site generator which supports multiple ‘back ends’ for providing URLs without file extensions. This looked like a useful way to support this.

**Comment by mholt** [comment]
Here you go: https://github.com/mholt/caddy-sqlite-fs

**Comment by mohammed90** [comment]
@dpk, you may also be interested in caddyserver/xcaddy#160, which addresses the `embedded` part. It builds atop https://github.com/mholt/caddy-embed.

**Comment by dpk** [comment]
Wow, thanks!!
