### ISSUE TITLE
v2 docs colour scheme choice

### ISSUE THREAD

**Issue by dv336699** [caddyserver/website#36]
Hi, first off, amazing work getting v2 up and running with the same simplicity and fundamentals of v1. Piece of art :clap:.

V1 website docs was a pleasant reading.
I can see some comparison with the colour scheme choice for v2 docs from [Docker documentation](https://docs.docker.com/get-started/overview/) (which for instance can be switched on/off).

Just did a really quick change using the colours from Caddy website and I believe this gives the reader a better reading experience - I'm not a designer, some colours might be better applied.

![Image](https://user-images.githubusercontent.com/930792/81156613-06be2f80-8f7e-11ea-936c-d2513add37e6.png)

Happy to provide a PR.

Best.

**Comment by hairyhenderson** [comment]
@diego-vieira can you elaborate on exactly what issues you have with the current colour schemes?

Personally I prefer the current colour schemes, so I don't really see the point in changing them right now. But, obviously a website's design is very much a subjective choice, so it's impossible for everyone to like the same design!

As for the one specific thing you mentioned which was the ability for colour scheme to be toggled, right now the site follows your system's light/dark mode settings, but there is a PR (#16) being worked on to allow that to be manually toggled.

If you could provide specific feedback on which elements of the site's design you have issues with, in particular, it would be very helpful!

**Comment by dv336699** [comment]
I thought it was just too blue and confused to follow, but that might just be me.

Thanks for your time.
