### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by allmors** [caddyserver/website#375]
First of all, caddy is very easy to use, but for some developers, the official documents are really very messy. Many key parts are just mentioned in one stroke. There is basically no explanation for the parts that developers need, but there are things that developers don’t need. A lot of explanations. The documentation really affects the spread of caddy. Especially after caddy2, the documentation is very simple. Basically, except for some basic examples, the advanced examples completely leave developers to guess.

**Comment by francislavoie** [comment]
What exactly are you finding lacking? Point to specific pages you think are problematic. Please don't be vague, it gives us nothing to work with.

I've just pushed a massive update to the docs two days ago https://github.com/caddyserver/website/pull/374. We're actively improving the docs. But without specific feedback, we can't improve.

**Comment by allmors** [comment]
> What exactly are you finding lacking? Point to specific pages you think are problematic. Please don't be vague, it gives us nothing to work with.
> 
> I've just pushed a massive update to the docs two days ago #374. We're actively improving the docs. But without specific feedback, we can't improve.

Thanks, I'll take the time to read the documentation

**Comment by francislavoie** [comment]
Yes, please do.

I hope you weren't writing those complaints without having read the docs, because that definitely wouldn't make sense.

**Comment by mholt** [comment]
(They might have meant that they will read the _updated_ documentation.)
