### ISSUE TITLE
quick-starts reverse-proxy --change-host-header

### ISSUE THREAD

**Issue by linquize** [caddyserver/website#38]
In https://caddyserver.com/docs/quick-starts/reverse-proxy

Document `--change-host-header` option. This option is frequently used when the upstream server requires correct `Host` header.

**Comment by mholt** [comment]
It's documented in the command line docs: https://caddyserver.com/docs/command-line#caddy-reverse-proxy

The quick start is just something to get you up and running in about 60 seconds. I don't want to have to demonstrate every flag in the quick-start guides.
