### ISSUE TITLE
JSON docs for http app take long time to load

### ISSUE THREAD

**Issue by jamesrf** [caddyserver/website#394]
When I go here: [https://caddyserver.com/docs/json/apps/http/](https://caddyserver.com/docs/json/apps/http/) and click on any of the keys in the json, for example "routes", the docs appear empty

**Comment by mohammed90** [comment]
It works, just slow. Give it a minute. It took around 1 minute for me.

**Comment by mholt** [comment]
Wow, that's awful.

I should try to improve that load time.

It's weird because the docs are supposed to be cached after the first load.

**Comment by jamesrf** [comment]
Not sure if something changed, but I just noticed this seems a lot faster today :)

**Comment by mholt** [comment]
We noticed it got fast again a few days ago and we're not sure why. No deploys, no reboots, no interventions... it just fixed itself.

**Comment by francislavoie** [comment]
I don't know what had happened here, but it has seemed fine for a while.
