### ISSUE TITLE
 matcher format for multiple sites share same definition

### ISSUE THREAD

**Issue by sospartan** [caddyserver/website#395]
I found put a space before comma will not parsed as two hosts, for example:    
```
abc.com , ab.com {
...
}
```
Is this a reasonable format? I'd like make a PR about it.
To quote the docs 

> If multiple sites share the same definition, you can list all of them together, either with spaces or commas.

Although the examples in the documentation are in the form of host immediately followed by a comma, this is, after all, not explicitly stated.

**Comment by mholt** [comment]
We should probably state that in the docs: there should be a space after the comma, not before. What you have there looks weird IMO :innocent: 

I'm going to transfer this to the website repo so we can work on it there.

**Comment by sospartan** [comment]
https://github.com/caddyserver/caddy/blob/e7ecc7ede2f0f749530b0c2e685b99954b9591ce/caddyconfig/caddyfile/parse.go#L260   
Noticed here is already handle the situation comma without space. I agreed these looks wired too. But I think support use comma to separating sites no matter spaces  will make caddyfile's syntax more fault tolerant. Space is quite easily neglected.  And the 'wired' part may handle it in 'formatter'.

**Comment by mholt** [comment]
We don't actually want "fault tolerant" Caddyfiles, we want consistent ones :slightly_smiling_face:

So the current behavior is correct, but we can clarify the specifics in the docs.

**Comment by francislavoie** [comment]
Fixing the parser edgecase here https://github.com/caddyserver/caddy/pull/6616

Also slight docs clarification: 6db3af5c3278b99c0e73a84c52fda02cf770c927
