### ISSUE TITLE
Website claims to use Fathom

### ISSUE THREAD

**Issue by Jak2k** [caddyserver/website#397]
The website claims to use Fathom, while Google Tag Manager is loaded

**Comment by mholt** [comment]
We do use Fathom: 
![image](https://github.com/caddyserver/website/assets/1128849/a676c9a6-274c-4aad-83d7-f6c814b92b1a)


![image](https://github.com/caddyserver/website/assets/1128849/085712a0-3c58-4015-8945-49bb1441804c)

Looks like I just forgot to add it to some of the site on the new pages. Will fix.

**Comment by Jak2k** [comment]
I now also shows up for me, but I still don't understand why Google Tag Manager is loaded. The point of Fathom is to be privacy-friendly.

**Comment by mholt** [comment]
ZeroSSL requested it be added. I don't think it's the newest GA version and if it's the old one it might not even be doing anything at this point since I think they shut down the old versions. I'll ask if we can remove it by now.
