### ISSUE TITLE
Chinese Editor for This Project?

### ISSUE THREAD

**Issue by vitsumoc** [caddyserver/website#402]
I'm writing to express my sincere gratitude for this project. I've learned a great deal from it and found it incredibly valuable.

I'm particularly interested in the possibility of creating multilingual documentation for this project.

I'm a native Chinese speaker with experience translating technical documentation. I've previously translated the [MQTT 5.0](https://vitsumoc.github.io/mqtt-v5-0-chinese.html) into Chinese and I'm confident that I can produce high-quality, accurate, and easy-to-understand documentation for your project.

Let me know if you're interested in my help. I'm happy to chat more about my qualifications and how I can contribute to the project.

**Comment by mholt** [comment]
We would be happy to have your help! We have many Chinese users.

Our current documentation is slated for rewriting (as soon as I get around to it). I hadn't considered multi-lingual support, but now I will try to do that when designing the new docs. I wonder what the best, simplest way is to do that? Do we use a query string, a path component, or something else?

/cc @WeidiDeng 

We can send you an invite to our Slack so you can chat more easily with the other maintainers. Just let me know your email address!

**Comment by vitsumoc** [comment]
my email address is vanchun032@gmail.com

I think the multi-lingual work should start from the documentation, so I did a small example. 

bb306da4ad49b17eecedf12a0f3e4216285537fb

In this way, all the content about Chinese doc will be concentrated in the `/src/docs/zh/` directory to avoid affecting the normal content update of the website. 

When the Chinese translation work almost done, you can add a multi-lingual entrance to the docs index and guide chinese users to `/docs/zh/`.

I think this looks good?

<img width="790" alt="zh" src="https://github.com/caddyserver/website/assets/31403302/637e499c-e419-4547-a7c7-6ae6f1e41f5c">

**Comment by mholt** [comment]
@francislavoie What do you think of using a language specifier in the URL for translated docs?

@vitsumoc LGTM. Did you already translate that much of it? (Machine translation is fine, as long as it's accurate -- so I'd expect a native speaker would verify any machine translations for correctness.) My worry is if you put a lot of work into translating our current docs, when we rewrite them, you will have a lot to translate again.

**Comment by vitsumoc** [comment]
I'd like to start by translating current docs in my own repository to familiarize myself with Caddy and gain some experience. Once the rewritten docs is complete, I can begin translating it and submitting PR.

By the way, I'm new to Slack. Will I receive notifications in Slack when there's progress on the rewritten work?

**Comment by mholt** [comment]
Sorry for the late reply, been a bit busy!

> I'd like to start by translating current docs in my own repository to familiarize myself with Caddy and gain some experience. Once the rewritten docs is complete, I can begin translating it and submitting PR.

You can do this, but again, it might be a lot of effort that is short-lived, if we rewrite the docs soon. That's why I'm suggesting that machine translation be used in the meantime. (Though I realize how it's often not as good as human translations.)

> By the way, I'm new to Slack. Will I receive notifications in Slack when there's progress on the rewritten work?

We'll definitely chat about it in Slack, it depends how you have your notifications set up. I'm not sure that we'll ping everyone but we might. In any case you can follow the conversation at least and configure your notifications! :)

**Comment by vitsumoc** [comment]
OK, I'm continuing the translation work, with machine translation, but it still takes some time.

If my work is finished before the new docs, I will submit a PR. Otherwise, I will directly follow up on the new docs. 

I have learned to use slack
