### ISSUE TITLE
Document {http.vars.trace_id} being set using tracing

### ISSUE THREAD

**Issue by trajano** [caddyserver/website#411]
This will allow people to add
```
header >x-request-id {http.vars.trace_id}
```

To the headers if they need it.

**Comment by francislavoie** [comment]
Makes sense, can be mentioned in here somewhere https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/directives/tracing.md

**Comment by francislavoie** [comment]
Done c43b2d482bd1b1289a66248edb0ec23b5083d906
