### ISSUE TITLE
Alternative syntax for www. subdomain redirects

### ISSUE THREAD

**Issue by Cryszon** [caddyserver/website#416]
I was unable to get [Common Caddyfile Patterns](https://caddyserver.com/docs/caddyfile/patterns) page's [Redirect `www.` subdomain](https://caddyserver.com/docs/caddyfile/patterns#redirect-www-subdomain) working (it caused "too many redirects"), but found [this community post](https://caddy.community/t/dynamically-redirect-www-to-non-www-vice-versa/9126) with a different syntax that worked.

Before (not working):

```Caddyfile
www.example.com {
	redir https://example.com{uri}
}

example.com {
}

:80 {
	...
}
```

After (working):
```Caddyfile
:80 {
	@www.example.com host www.example.com
	redir @www.example.com https://example.com{uri}
	...
}
```

Maybe the documentation could be updated to include the alternate syntax or replace the current one.

**Comment by mohammed90** [comment]
The example on the website doesn't have the `:80` site, so the example is still correct. I assume your websites are behind Cloudflare which (based on your Cloudflare configuration) enforces HTTPS before passing the request to Caddy; and Cloudflare connects to Caddy over HTTP, which Caddy rejects to only be connected over HTTPS thus causing redirect loop. If yes, that'd be a very specific situation that is not always applicable.

**Comment by Cryszon** [comment]
I'm not using Cloudflare, but do have a reverse proxy that handles HTTPS before Caddy. Specifically Coolify, which handles HTTPS and uses Traefik to route requests to a Docker container that's running Caddy.

What is the correct way to handle redirects in this case and are there any other things I should take into consideration with this configuration? Is there some documentation I missed for this specific setup?

**Comment by mohammed90** [comment]
You could simply do this:

```
http://www.example.com {
	redir https://example.com{uri}
}

http://example.com {
 # ...
}
```
