### ISSUE TITLE
[doc] Update forward_auth document to reflect latest change in authelia

### ISSUE THREAD

**Issue by christaikobo** [caddyserver/website#421]
The document on caddy and authelia is inconsistent, using different example config:

https://caddyserver.com/docs/caddyfile/directives/forward_auth#authelia
https://www.authelia.com/integration/proxies/caddy/#subpath

I have searched around for a bit and it seems authelia changed its api:
https://fossies.org/diffs/authelia/4.38.9_vs_4.38.10/docs/content/blog/release-notes-4.38/index.md-diff.html

So maybe it is better to update caddy's doc to reflect that?

**Comment by james-d-elliott** [comment]
I'll take a close look at this today. Thanks for pinging me.

**Comment by james-d-elliott** [comment]
Just confirming that the `uri /api/verify?rd=https://auth.example.com` should be updated to `uri /api/authz/forward-auth`.

Technically the /api/verify example still works, just it's not our recommended option anymore.

**Comment by francislavoie** [comment]
Okay sounds good. Is the redirect target configured on authelia now instead?

**Comment by james-d-elliott** [comment]
Correct, this was added as part of the multi-domain config. There is still a query argument but it's changed for those new endpoints and is intended on just being an override.

**Comment by francislavoie** [comment]
Updated, thanks!

https://github.com/caddyserver/website/commit/12e02d62b0534da21e1bf26112a3a92e00846c17
