### ISSUE TITLE
Typo/error in Caddyfile Tutorial

### ISSUE THREAD

**Issue by ethereal-engineer** [caddyserver/website#423]
I am going through the tutorial and docs right now, so will report any inconsistencies or such as I go, as a help.

> Either the file server will **write** a static file, or the reverse proxy will proxy the request to a backend.

Pretty sure you wanted to say _read_, or _serve_. Because _write_ doesn't make sense in this context.

**Comment by ethereal-engineer** [comment]
This is under Matchers, btw.

**Comment by mholt** [comment]
Oh, I think it's referring to writing a static file to the response. We could clarify this.

**Comment by francislavoie** [comment]
Cleaned it up: 58527b688a9527f2accdb46738de9ac313551666, thanks!
