### ISSUE TITLE
Mention file_server from the root directive docs page

### ISSUE THREAD

**Issue by dontlaugh** [caddyserver/website#44]
Migrating from v1 to v2 Caddyfile here. I might be dense, but it took me a while to get caddy to just serve my index.html file. I needed `file_server` as well as `root`. I eventually had success with this configuration:

```
coleman.codes {
    root * /opt/blog/public
    file_server
}
```
You might consider linking to the `file_server` directive from the `root` directive's docs page, or perhaps providing an example that combines both on both pages.

**Comment by francislavoie** [comment]
That's good feedback! Thanks, I'll look into it.

**Comment by francislavoie** [comment]
See #45, is that what you had in mind?

**Comment by dontlaugh** [comment]
Yes! That's going to help folks.
