### ISSUE TITLE
mobile 'module' page formatting issue

### ISSUE THREAD

**Issue by ShalokShalom** [caddyserver/website#51]
![Screenshot_2020-05-29-12-25-59-26_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/83250153-f3cb0380-a1a7-11ea-9ffb-da085dd0a769.jpg)

https://caddyserver.com/docs/modules/

**Comment by mholt** [comment]
Any idea how to fix it?

**Comment by polarathene** [comment]
@mholt you can add `overflow: auto` to your `#module-list-container` selector. This will add vertical or horizontal scrollbars when the content overflows it's boundaries.In this case that's a horizontal scrollbar that would on a desktop view require scrolling down to the bottom of the table to use, but I think for mobile the use should be able to pan with their finger horizontally.

An alternative is `min-width: fit-content` or `min-width: min-content`/`min-width: max-content`, these will make the whole page horizontally scrollable when the content for that element is too wide, however your CSS elsewhere does not adapt to center align  to that correctly, so I'd just stick with the `overflow` fix.

**Comment by mholt** [comment]
Thanks for the tip! That did it.
