### ISSUE TITLE
Website as a amazing example / LICENSE

### ISSUE THREAD

**Issue by cameronelliott** [caddyserver/website#57]
Hi, I am not sure of the best way to put this...
I see there is no LICENSE file, and I would guess that is by design,
I can understand why the team wouldn't want people to use everything in this repo as-is for other projects.

But, I have been thinking about this a few weeks, and this repo does something very very special that might be worth figuring out how to share:

This repo shows how to build a first-class website without using a static site generator, and instead using Caddy.  For example having a 'docs' section using markdown and Caddy is pretty awesome without having to get a static generator involved.

I think this repo uses hand-crafted CSS and not Bootstrap or Tailwind, which would really best suit my needs, but I think it is worth pointing out that a first-class website template like this using, say, Tailwind with a permissive license might really help a lot of people adopt Caddy instead of a static site.

So, maybe there is a way to add a license that allows people to build from this example without hurting the Caddy project in some way?

I also think maybe a site or project for "Caddy themes" or "Caddy templates" could be a really awesome way to show the power of using Caddy INSTEAD of a static site generator.

This is one way I would like to use Caddy, but would really be helped by permissive license examples using either Bootstrap or Tailwind.

Thanks for making Caddy!

**Comment by francislavoie** [comment]
You may have already noticed, but the docs point to this repo as an example how to use templates https://caddyserver.com/docs/caddyfile/directives/templates#examples

I'll let @mholt give a more definitive answer regarding a license, but feel free to use the contents as a basis for a static site if you need!

If you want to make some site templates as examples, that would be great. I don't think it's really in our plans to spend the time to make those sorts of examples ourselves right now, but as always, we'd love to invite the community to help with that!

**Comment by mholt** [comment]
Interesting request. I don't think it really makes any sense to license the Caddy website for general use. I mean, this is the _Caddy_ website. If people started putting up their own derivative works it would be really confusing. There should only be one Caddy website.

That said, feel free to use whatever techniques you learn from this repo. We can't copyright or patent ideas, and I hope how we do things will serve as a good example for other projects.

For any more examples, there's always our wiki, which anyone can contribute to: https://caddy.community/c/wiki/13
