### ISSUE TITLE
Typo in config example.

### ISSUE THREAD

**Issue by martyschaer** [caddyserver/website#58]
The very last example on [this page](https://caddyserver.com/docs/caddyfile/directives/header#header). Reads:

`header           Cache-Control max=age=3600`
But should be (`-` not `=` between `max` and `age`):
`header           Cache-Control max-age=3600`

**Comment by francislavoie** [comment]
Huh, thanks! I thought we had fixed that one. Guess not.

**Comment by martyschaer** [comment]
It appears to be fixed already in 9594e4bc4b.
Sorry about that.

**Comment by francislavoie** [comment]
Actually that commit fixed one but not both :joy:
