### ISSUE TITLE
Json config structure section not working

### ISSUE THREAD

**Issue by endelwar** [caddyserver/website#62]
After the last website upgrade the json doc section is not working as expected: clicking on https://caddyserver.com/docs/json/ give an empty page, same thing accessing the direct links like https://caddyserver.com/docs/modules/http.reverse_proxy.transport.http

**Comment by francislavoie** [comment]
Works for me. Try a hard-refresh of your browser (ctrl+shift+f5)?

The Caddy website switched servers entirely but the JS assets are likely still cached by your browser.

**Comment by endelwar** [comment]
I had to clear browser cache, then it worked right. Maybe versioning assets during build could help.

**Comment by francislavoie** [comment]
Yeah the JS is actually just hand-written stuff, not NPM + webpack bundled stuff. Simpler not to, really. But you're not wrong.
