### ISSUE TITLE
Reorganize docs-nav.html

### ISSUE THREAD

**Issue by Merith-TK** [caddyserver/website#65]
So i am going through and rebuilding the docs-nav.html embed in markdown, and so far it is going Very good as the generated HTML lines up near perfectly with the css used! Aside from the catagory titles, however it does work, 
```md
< /src/includes/docs-nav.md >

- [Welcome](/docs/)
- [Wiki 🔗](https://caddy.community/c/wiki/13)

#### Get Caddy
- [Download](/docs/download/)
- [Build from Source](/docs/build/)
- [Install](/docs/install/)

#### Tutorials
- [Getting Started](/docs/getting-started/)
- [Quick Starts](/docs/quick-starts/)
    - [Using the API](docs/quick-starts/api)
``` 
```html
<!-- /src/includes/docs-nav.html -->
{{$markdownFilename := default "docs-nav"}}
{{$markdownFilePath := printf "/includes/docs-nav.md"}}
{{$markdownFile := (include $markdownFilePath | splitFrontMatter)}}
{{$title := default $markdownFilename $markdownFile.Meta.title}}
<nav class="sidebar">
	{{markdown $markdownFile.Body}}
</nav>
```
generates as so, which is close enough to not affect users
![](https://i.imgur.com/wqw3bmz.png)

**Comment by mholt** [comment]
I don't know if this is going to be accomplishable (accomplished? possible? is that a word?) in pure markdown. What's wrong with what we have now?

**Comment by Merith-TK** [comment]
I was thinking future proofing also making it easier to add more docs faster as they dont have to format the html

And it is possible, go ahead and try it yourself with the edits i showed, it does work.

**Comment by polarathene** [comment]
Would this be related to a side nav for current page contents?(not the left sidebar) Similar to what Traefik docs have? Especially for pages with many headers each with multiple paragraphs it'd be useful. Some pages add a list of links at the start of the document as a workaround.

**Comment by Merith-TK** [comment]
it certainly could be a step closer,
