### ISSUE TITLE
Trailing slash on docs causes page to not load

### ISSUE THREAD

**Issue by Merith-TK** [caddyserver/website#66]
```
2020/07/23 18:39:15.870 ERROR  http.log.error  template: /docs/index.html:4:20: executing "/docs/index.html" at <include $markdownFilePath>: error calling include: open src\docs\markd
own\install\.md: The system cannot find the path specified.     {"request": {"method": "GET", "uri": "/docs/install/", "proto": "HTTP/1.1", "remote_addr": "[::1]:54320", "host": "localhost:2015", "headers": {"User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Accept-Language": ["en-US,en;q=0.5"], "Accept-Encoding": ["gzip, deflate"], "Connection": ["keep-alive"], "Referer": ["http://localhost:2015/docs/"], "Upgrade-Insecure-Requests": 
["1"]}}, "duration": 0.0030252, "status": 500, "err_id": "tp3q5fbby", "err_trace": "templates.(*Templates).executeTemplate (templates.go:305)"}
```
It appears that when it tries to load the markdown file, it loads most of the url correctly, but puts a `/` right before the markdown extension

**Comment by mholt** [comment]
Interesting, which link did you follow that produces this error? I haven't experienced this.

**Comment by Merith-TK** [comment]
honestly, i dont really know. 
it is live on the main docs as well, go to any page and put a extra `/` at the end, 
![image](https://user-images.githubusercontent.com/10422110/89092120-c9dabc80-d363-11ea-89b0-760d335bb114.png)
![image](https://user-images.githubusercontent.com/10422110/89092126-d19a6100-d363-11ea-98c3-bbda9bd00203.png)

**Comment by mholt** [comment]
Is there a bad link that is doing this though? I mean, you could add `sfdlkjsdfkj` to the end of any page, too, and it won't work. I am not really surprised that a bad URI is not working?

Anyway, I'll close this, as it doesn't seem to be a real problem. (But maybe I just don't understand it.)

**Comment by Merith-TK** [comment]
No bad links on the page, but people generally add a slash to the end of
urls, and this can be a problem.
