### ISSUE TITLE
Custom caddy+plugins build server does not provide versioned URL in Location header

### ISSUE THREAD

**Issue by lucafavatella** [caddyserver/website#7]
I prefer downloading a custom binary built online retrieving it from a versioned link, cache it locally in a file containing the build version in the name and use it for development and deployment - so I know the deployed version works.

The caddyserver.com [Download page](https://caddyserver.com/download) presents the user (let us take linux amd64 + jwt plugin) with link `https://caddyserver.com/download/linux/amd64?plugins=http.jwt`, that:
* When queried with GET, the server does not return a `Location` header;
* When queried with HEAD, the server returns a non-versioned `Location` header.

I see the following issues:
* The `Location` header in the HEAD response is non-versioned - actually not useful as it replays the path in the HTTP request;
* The headers in HEAD and GET responses are different.

----

Evidence 1:
```
$ curl -I https://caddyserver.com/download/linux/amd64?plugins=http.jwt
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location
Content-Security-Policy: style-src   'self' https://fonts.googleapis.com;                                         script-src  'self' data: https://www.google-analytics.com https://checkout.stripe.com;                                     img-src     'self' data: https:;                                        font-$
rc    'self' data: https: blob:;                                     media-src   'self' https:;                                      connect-src 'self' https:;                                         object-src  'none';
Content-Type: text/plain; charset=utf-8
Date: Fri, 28 Apr 2017 14:39:10 GMT
Location: /download/linux/amd64?plugins=http.jwt
Referrer-Policy: no-referrer-when-downgrade
Server: Caddy
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

```

Evidence 2:
```
$ curl -v https://caddyserver.com/download/linux/amd64?plugins=http.jwt > foo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 138.68.240.78...
* Connected to caddyserver.com (138.68.240.78) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: caddyserver.com
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /download/linux/amd64?plugins=http.jwt HTTP/1.1
> Host: caddyserver.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Location
< Content-Disposition: attachment; filename="caddy_v0.10.0_linux_amd64_custom.tar.gz"
< Content-Security-Policy: style-src   'self' https://fonts.googleapis.com;                                       script-src  'self' data: https://www.google-analytics.com https://checkout.stripe.com;                                     img-src     'self' data: https:;                                        font-$
rc    'self' data: https: blob:;                                     media-src   'self' https:;                                      connect-src 'self' https:;                                         object-src  'none';
< Content-Type: application/x-gzip
< Date: Fri, 28 Apr 2017 14:39:28 GMT
< Referrer-Policy: no-referrer-when-downgrade
< Server: Caddy
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< Transfer-Encoding: chunked
<
{ [227 bytes data]
100 5208k    0 5208k    0     0  1209k      0 --:--:--  0:00:04 --:--:-- 1310k
* Connection #0 to host caddyserver.com left intact
```

For comparison, the previous download server used to returned a versioned `Location` header, that was useful:
```
$ curl -I 'https://caddyserver.com/download/build?os=linux&arch=amd64&arm=&features=jwt'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location
Content-Disposition: attachment; filename="caddy_linux_amd64_custom.tar.gz"
Content-Security-Policy: style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://maxcdn.bootstrapcdn.com; script-src https://www.google-analytics 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:; img-src 'self' data: https:; font-src 'self' https: data: blob:; media-src 'self' https: data: blob:; connect-src 'self' https:; object-src 'none';
Content-Type: text/plain; charset=utf-8
Date: Wed, 29 Mar 2017 11:39:47 GMT
Expires: Mon, 01 Jan 0001 00:00:00 GMT
Location: /download/builds/172103150106950/caddy_linux_amd64_custom.tar.gz
Server: Caddy
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

```

----

The entry point appears to be https://github.com/caddyserver/website/blob/02908c73b931437a7faa4f95bfbea33b240abeaf/Caddyfile#L28 that I think proxies https://github.com/caddyserver/devportal/blob/5984e33bf04aa2e545029bcf438fc55781fed05e/cmd/devportal/main.go#L13
The difference in HEAD/GET headers may be in https://github.com/caddyserver/devportal/blob/5984e33bf04aa2e545029bcf438fc55781fed05e/builds.go#L539-L540

**Comment by mholt** [comment]
@lucafavatella Thanks for your investigation, very thorough!

The old server's Location header was not versioned. That number in the URI was a "hash" of the build configuration, because every build was cached. Both the old build server and the new one build the latest released versions of Caddy and the plugins you requested. The new build server also caches builds, but its location on disk is no longer revealed in the Location header. The new build server clears invalidates cache items when plugins or new Caddy version is released.

<sup>(Internally, the build worker does take a Caddy version and a list of plugins and their versions, so builds can be custom-versioned. However, I am not convinced yet that I want to enable downloading old versions, especially for an initial release. Upgrading is important. But that's a rabbit hole for another discussion.)</sup>

The HEAD request is to ask for a build and be notified when it is finished by the request completing. The GET request actually downloads it.

Everything seems to be working as expected. _Maybe_ someday we'll allow customizing the versions of released plugins or Caddy itself, but not right now. Maybe closer to 1.0.

Thanks again! I appreciate your diving into the code.
