### ISSUE TITLE
HTTPS error for www.caddyserver.com

### ISSUE THREAD

**Issue by connorspeers** [caddyserver/website#70]

**Comment by francislavoie** [comment]
You're looking for https://caddyserver.com/, the `www.` subdomain isn't served.

**Comment by connorspeers** [comment]
Makes sense, but why the CNAME then?

<img width="535" alt="Screen Shot 2020-07-30 at 12 58 59 AM" src="https://user-images.githubusercontent.com/2181051/88882434-f1b10f80-d1ff-11ea-90a7-6d04162c244f.png">

Further, your Caddy instance is definitely responding to the requests to www.caddyserver.com on port 80.

<img width="617" alt="Screen Shot 2020-07-30 at 1 01 11 AM" src="https://user-images.githubusercontent.com/2181051/88882588-4b193e80-d200-11ea-90f4-32a79ad75b00.png">

Could ignore this as a non-issue, but I'm curious, what settings in the Caddyfile would cause the www certificate to not work server side?

**Comment by connorspeers** [comment]
Ohhh my bad, the location is just redirecting to https://www.caddyserver.com.

That's my bad. Thanks!

**Comment by francislavoie** [comment]
The Caddyfile used to serve the site just doesn't have `www.caddyserver.com` listed. `www.` is basically just a legacy relic of the web, there's basically no reason to use it for new sites at this point.

**Comment by connorspeers** [comment]
I found this issue when I accidentally typed caddyserver.org into the URL bar for firefox. When FF didn't find that server, it automatically tried www.caddyserver.org. When it didn't find that one, said it couldn't be found, and I saw I used .org instead of .com.

After replacing org with com, I got the SSL internal error. I totally agree, www is antiquated, but it remains true that I'm receiving an "internal" SSL error from your server. Doesn't feel like that's the appropriate response, or am I wrong here?

This wouldn't happen if the CNAME record didn't exist. The browser would error with a server not found.

Fun stuff!

**Comment by francislavoie** [comment]
No that's exactly the correct response. The browser tries to execute a TLS handshake, but the server doesn't have a cert for that domain, so the handshake fails.

You're right that wouldn't happen if there was no CNAME, but... whatever? 😛

**Comment by connorspeers** [comment]
See, to me, that's like having a doorway to nowhere. But whatever floats your boat. ⛵️

Thanks for the help!

**Comment by mholt** [comment]
@connorspeers What link did you follow to get to that address? AFAIK we don't use that domain at all on any of our web pages.

**Comment by connorspeers** [comment]
I didn't get it from anywhere, I tried it by mistake, like I said. Firefox apparently automatically attempts the www subdomain before giving up if it can't find the root domain I guess? Try it on FF on macOS. If you go to a nonexistent domain, it inexplicably throws the www on there before showing you the server not found error. Probs a legacy browser behavior or something.

To recreate exactly how I discovered this:

1. Open your 5th beer for the night, and load up FF 79 on Catalina. Type "caddyserver.org" in the URL bar because who needs bookmarks when you have fingers and a brain and are entirely too confident in your ability to remember URLs?
2. Realize that you drank too much to properly remember URLs and the "server not found" error you got is because you typed ".org" instead of ".com". Completely miss the fact that the "www." was still hanging out in front of the URL because *why* would it be there in the first place, you didn't type that shit! Nothing to worry about.
3. Be startled by the first SSL error you've seen in like three hours and wonder "What's up with that? I was just on this site back on beer 1!"
4. See the stupid "www" freeloader. Remove it and try the root domain. It works fine. "Oooooh, it's just the www subdomain." Hmm...
5. `dig www.caddyserver.com` "Wait, DNS record exists for www subdomain but server responds with SSL error... Is that a bug? Do I get to file my first pandemic bug!? I get to file my first pandemic bug!"
6. File bug.
7. Super on-top-of-things developer responds two or three minutes later, blowing your own personal record for rapid response out of the water. Wish you could be more like that developer as you open beer 6.
8. Developer: "You're looking for https://caddyserver.com/" etc. etc.

**Comment by francislavoie** [comment]
❤️ 😂

Thanks for that write-up and the laugh!
