### ISSUE TITLE
Linting / Conventions

### ISSUE THREAD

**Issue by polarathene** [caddyserver/website#75]
Minor quibble, would there be any interest in addressing this a little? 

Including an `.editorconfig` file for example is an easy way to document some basic style conventions and some editors will automatically recognize and respect those rules without a contributor needing to think about it, potentially reducing some review noise.

We could also add some automated linting/corrections. The Gatsby project runs a pre-commit git hook so that style conventions are applied before publishing/pushing commits for a PR.

As this project is documentation/prose focused, [`textlint`](https://textlint.github.io/) may also be of interest. Although I wouldn't automate the suggested corrections, but some are pretty nice, you can try with markdown content in [their online playground](https://textlint.github.io/playground/) to see what it spots.

We could automate with Github Actions and leverage something like [reviewdog](https://github.com/reviewdog/reviewdog), they have [a recent beta action `action-suggester`](https://github.com/reviewdog/action-suggester), which allows for reporting the changes on a PR with commit suggestions to selectively apply or discuss. That might be helpful with PR reviews?

**Comment by mholt** [comment]
For human-consumed text I tend to find linters too opinionated and difficult to configure/manage.

Textlint seems buggy; it shows warnings about "TODO" on the h1 line where it doesn't exist. It also annoyingly complains about the term "very" when in reality there's nothing wrong with it.

As most of our content is technical documentation, I'm not too worried about prose -- but happy to accept feedback about specific parts of the documentation with specific suggestions leading toward improvements.

Thanks!

**Comment by polarathene** [comment]
And style convention lints for contributions? I noticed some inconsistencies such as the amount of blank lines being used to separate content, there is single blanks between paragraphs, but before a new header there is 1-3, often mixed.

It'd be handy for fenced code blocks too, although I'm not sure if there is a lint for that which can enforce tabs. `editorconfig` can be slightly helpful, or for more advanced rules and linting to maintain consistency through the docs we could leverage `markdownlint`, I [opened an issue there](https://github.com/DavidAnson/markdownlint/issues/312) regarding fenced code block indentations rule so tabs could be supported.

---

Regarding `textlint`, I understand that TODO gripe, I'm not sure if that's an issue with their playground. Those can be disabled though and only rules that are worthwhile can be enabled. One that looked useful for example was capitalization, it caught quite a few lines that start with lower case or in a list are inconsistent.

Some of it's prose suggestions aren't great, hence the mention of not automatically applying them, but that feature can just be disabled if there's value elsewhere from it.

**Comment by mholt** [comment]
> I noticed some inconsistencies such as the amount of blank lines being used to separate content, there is single blanks between paragraphs, but before a new header there is 1-3, often mixed.

Ah, that's because I personally prefer a few more lines before headers since I think they're easier to see when scrolling through a document or scanning it visually. But that's just my personal preference and I don't enforce the multiple empty lines. :)
