### ISSUE TITLE
Caddyfile TLS does not disable auto_https when provided a cert and key

### ISSUE THREAD

**Issue by polarathene** [caddyserver/website#79]
https://caddyserver.com/docs/caddyfile/directives/tls

> **<cert_file>** and **<key_file>** are the paths to the certificate and private key PEM files. Specifying just one is invalid; specifying both will disable automatic HTTPS.

- Does not disable automatic HTTPS
- Using the JSON API for `ignore_loaded_certificates: false` does not disable either (assuming this is manually loading)
- Differs from `tls internal` with `auto_https off` as the certificate is still provided. 

---

**Caddyfile:**

```caddy
{
  #local_certs
  #auto_https disable_redirects
}

192.168.1.42:8000, example.localhost:8000 {
  #tls internal
  tls /tls/example.localhost-cert.pem /tls/example.localhost-key.pem
  reverse_proxy localhost:9000

  # Unrelated to reverse_proxy, same behavior:
  #root * /usr/share/caddy
  #file_server
}
```

- Providing my own cert and key PEM files is working as expected. 
- Visiting `http://example.localhost` will redirect to `https://example.localhost:8000`, which should not happen if `auto_https` is disabled?
- `auto_https` either configured to `off` or `disable_redirects` work as intended. Just `auto_https` is implicitly enabled otherwise.

Initially seemed that `auto_https` config had no effect, but was due to `301` redirects previously issued, tested again in Chrome Incognito (closed session after each config change), which confirms the findings above.

---

Do these docs need to be corrected?

**Comment by polarathene** [comment]
Additional observation. `auto_https off`, the webpage can still successfully be accessed via `https://example.localhost:8000`, whereas when using `tls internal` this would fail(`ERR_SSL_PROTOCOL_ERROR`, log states due to no certificate available) as TLS is not setup due to `auto_https off`. 

Is that inconsistency expected? It seems to be due to Caddy not generating a certificate due to `auto_https off`, but when I explicitly provide a certificate there's no error to raise, the certificate is used for TLS.

**Comment by polarathene** [comment]
I have tried to use the JSON config API: `http://localhost:2019/config/apps/http/servers/srv0/automatic_https/` with POST:

```JSON
{
  "ignore_loaded_certificates": false
}
```

`false` or `true` doesn't seem to matter. [Automatic HTTPS activation section](https://caddyserver.com/docs/automatic-https#activation):

> Manually loading certificates (unless  [this config property](https://caddyserver.com/docs/json/apps/http/servers/automatic_https/ignore_loaded_certificates/)  is true)

Explicitly setting that to `false` should result in automatic https being disabled in this config?

**Comment by polarathene** [comment]
[Created a community thread](https://caddy.community/t/caddyfile-tls-does-not-disable-auto-https-when-provided-a-cert-and-key/9734) due to inactivity on this issue.

**Comment by mholt** [comment]
Sorry, I've actually had this tab open for a couple of weeks and finally got them trimmed down so they all fit on one screen. I'll revisit this shortly!

**Comment by mholt** [comment]
> I'll revisit this shortly!

Well so much for "shortly" but to be fair yours was the last notification on my backlog of 110 which I finally cleared out today. Yay. This is the last one.

Anyway...

How about if we update the documentation to say that if you provide your own certificate, Caddy will not attempt to manage a certificate for that site. (The redirects still happen.)

**Comment by king5300** [comment]
[]()

**Comment by polarathene** [comment]
Sorry about the late reply, I didn't seem to notice the earlier notification in September.

> How about if we update the documentation to say that if you provide your own certificate, Caddy will not attempt to manage a certificate for that site. (The redirects still happen.)

What does Caddy do certificate management wise beyond redirects and provisioning (ACME/self-generation)? The issue was raised to clarify what the documentation was claiming, it's either incorrect or a bug?

> **<cert_file>** and **<key_file>** are the paths to the certificate and private key PEM files. Specifying just one is invalid ~; specifying both will disable automatic HTTPS~.

We could just drop the questionable part of the documentation instead?

**Comment by mholt** [comment]
> We could just drop the questionable part of the documentation instead?

Sure, that sounds good to me. Done.

**Comment by mcrapts** [comment]
I don't understand how this works. The website reads:

> Any of the following will prevent automatic HTTPS from being activated, either in whole or in part:
> 
> Explicitly disabling it
> Not providing any hostnames or IP addresses in the config
> Listening exclusively on the HTTP port
> **Manually loading certificates (unless this config property is true)** 

The latter appears not to be true. The following does not stop Caddy from trying to obtain a certificate:
```
subdomain.mydomain.com {
  tls cert.crt key.pem
  reverse_proxy my-service:80
}
```

The only way I can stop automatic certificates is by disabling auto_https. But that's not necessarily something I want, because the redirects are fine and it seems impossible to have only automatic redirects. Am I missing something? Or is the documentation incorrect? Either way I think there should be an option to specify a manual certificate and disable automatic certificates without disabling automatic redirects on a granular level (so not the auto_https global option).

I'm interesting in hearing your opinion @mholt .

**Comment by francislavoie** [comment]
@mcrapts What are the SANs in the certificate? If your domain isn't listed in the certificate, then Caddy will fetch one that does.

**Comment by mcrapts** [comment]
SAN includes a wildcard for my domain: *.mydomain.com.

**Comment by francislavoie** [comment]
Caddy looks for an exact match for the SAN in loaded certificates. If it's a wildcard cert then you should use `*.example.com` as your site address so that it matches the SAN. You can structure your config like this: https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates

**Comment by mcrapts** [comment]
I see, that clears things up. It is still rather verbose. My alternative so far has been to disable auto_https and use a snippet:
```
(use_subdomain) {
  http://{args.0} {
    redir https://{args.0}{uri}
  }
  https://{args.0} {
    tls cert.key key.pem
    reverse_proxy {args.1}
  }  
}
```
This gets the job done as well. Still, I'd rather have an option to explicitly disable certificate fetching.
