### ISSUE TITLE
https://getcaddy.com is down due to SSL cert issue 

### ISSUE THREAD

**Issue by sshivaji** [caddyserver/website#80]
I get the NET::ERR_CERT_COMMON_NAME_INVALID exception in Chrome and in firefox the exception is 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

I am not sure if this is the right place to report it. However, this will impact all caddy v1 download scripts. Is caddy v1 no longer available for download from sites?

![Screenshot from 2020-08-23 02-11-20](https://user-images.githubusercontent.com/1430554/90975082-f6f33880-e4e5-11ea-8094-4185f4bc1a80.png)

**Comment by mholt** [comment]
Yeah, that site is no longer active. And I no longer administer that domain, but I'll put in a note for the admins to update the DNS records or something.

**Comment by sshivaji** [comment]
I feel it might be easier to just put a redirect from that site to the new caddy v2 and quote that this is no longer maintained (maybe even a 301)? Sad to hear that that domain is no longer maintained. I can bet many production deployments still have that site in their scripts to download caddy.

**Comment by sshivaji** [comment]
I realize another problem. If the domain getcaddy.com is no longer administered by the caddy team, is there not a risk that the new owner of the domain can potentially inject a binary with malware that can be used on old caddy v1 prod sites?

**Comment by mholt** [comment]
I submitted a request and the admins of the domain have already updated the DNS records to point to a machine we control again.

The script emitted a deprecation notice for a good 6 months at least, and Caddy 1 had no updates in that time either.
