### ISSUE TITLE
error attempting to register plugin on caddy server.com

### ISSUE THREAD

**Issue by rayjlinden** [caddyserver/website#83]
Not sure if this is the right place to report this.  I was trying to "register" my plugin: https://github.com/lindenlab/caddy-s3-proxy

I got the following error:
```
Sorry, something went wrong:

unable to scan modules in package https://github.com/lindenlab/caddy-s3-proxy

Please include this error ID if reporting:
a5970848-2bf5-43ea-bb0f-5035f71683af
```

**Comment by mholt** [comment]
Thanks for the report! Will look into it ASAP.

**Comment by mholt** [comment]
@rayjlinden Go module paths do not have schemes (they aren't URLs): `https://` - remove that and it should work.

**Comment by francislavoie** [comment]
@mholt maybe you could add a validation step for that, so others don't make that mistake?

**Comment by rayjlinden** [comment]
Thanks - that works better.  Cool system for registering plugins!  I like it!

**Comment by mholt** [comment]
Cool, glad you like it and that it worked!
