### ISSUE TITLE
website plugin registration - problem with refresh

### ISSUE THREAD

**Issue by rayjlinden** [caddyserver/website#85]
I registered a plugin the other day.  Since then I made an update and shipped a new version - one that changed the comments on the handler struct that shows the a description of the package on the downloads page.

I hit the "rescan" button,  It reported it rescanned (immediately I might add, which seemed suspicious.)  However, the description of the package that come from those comments have not been updated.  So it appears to me the reason feature is broken.

**Comment by rayjlinden** [comment]
I also tried deleting the package and re-adding it.  I was hopping that would cause it to rescan.  This also did not work - the old information is still there.  Which is rather unfortunate as the Caddyfile spec has changed considerably for my plugin.

**Comment by mholt** [comment]
I'm working through a backlog right now but will take a look at this soon. Can you tell me which plugin it is in the meantime?

**Comment by rayjlinden** [comment]
github.com/lindenlab/caddy-s3-proxy

**Comment by mholt** [comment]
Thanks.

Haha, so.... I am switching to a new dev workstation and my DB tool that I'm used to isn't available for Linux so it's going to take me a little longer to get it set up and to be able to look into this in detail.

**Comment by rayjlinden** [comment]
Any update on this issue?

**Comment by mholt** [comment]
Sorry, not yet. I'll post here when I have an update.

**Comment by mholt** [comment]
Which commit(s) specifically do not show up on https://caddyserver.com/docs/modules/http.handlers.s3proxy ?

**Comment by mholt** [comment]
@rayjlinden Can ya help me out? :) I started looking at this but could not find a discrepancy. What is missing?

**Comment by rayjlinden** [comment]
The caddy site mentions the directive “ canonical_uris” which was deleted
from my plugin many many versions ago.

Ray

**Comment by mholt** [comment]
@rayjlinden I've deleted it from the DB, please try re-adding it? I need to figure out a better way to have it refresh the docs.

**Comment by king5300** [comment]
[]()

**Comment by mholt** [comment]
@rayjlinden Did that work for you?

**Comment by rayjlinden** [comment]
Yes.  When I re-added the plug-in the data was correct.  Of course, that approach resets stats like number of downloads, etc.

Ray

**Comment by mholt** [comment]
Ok good. Thanks for checking!

(And number of downloads is the only stats... very simple system.)
