### ISSUE TITLE
Default log format is json, not console

### ISSUE THREAD

**Issue by kiranjthomas** [caddyserver/website#88]
The default format for logs is listed as `console` here: https://caddyserver.com/docs/caddyfile/directives/log#format-modules

However, if a consumer does not provide a format, the default is actually `json`.

**Comment by francislavoie** [comment]
Actually the console formatter checks whether the output is a TTY or not, and if not, outputs as JSON. You can see this if you run `caddy validate` from your terminal.

**Comment by francislavoie** [comment]
You can see the logic here:

https://github.com/caddyserver/caddy/blob/85152679ce910d0993a2902ec00d199b8cc14e4d/logging.go#L673-L683

But yeah you're right we can improve the docs to mention that fact (that default is console if a terminal, otherwise JSON)

**Comment by kiranjthomas** [comment]
Very cool!

I just created a fork and would be happy to update the docs per your last comment.

**Comment by francislavoie** [comment]
That'd be great, thanks!
